- .github/workflows/ci.yml
This PR adds a pipeline that uses Github Actions for basic validations around code.
> chore: add basic setup for CI

- CONTRIBUTING.md
- README.md
- package.json
This PR:
- updates README to provide brief information
- adds `CONTRIBUTING.md`
- adds `build` to `package.json#scripts`
> docs: update README, add contributing guide, add "build" command

- .github/workflows/ci-change.yml
- packages/core/src/__styles.ts
This PR adds an additional check powered by Github Actions to ensure that change files are present for changes inside PRs.
> chore: add check for change files

- change/@griffel-babel-preset-c2a5937a-013f-4709-8841-a4b9377bf7f9.json
- change/@griffel-jest-serializer-f4b054c4-75d8-42f9-b6a0-87572e29c1bb.json
- packages/babel-preset/README.md
- packages/jest-serializer/README.md
Fixes some typos in README files.
> docs: fix typos in READMEs

- change/@griffel-react-e715c47b-472e-43ec-b489-8fb77fcb9f90.json
- packages/react/src/stories/ComponentStyles.stories.tsx
- packages/react/src/stories/DOMRendererFilter.stories.tsx
- packages/react/src/stories/index.stories.tsx
- packages/react/src/stories/makeStyles.stories.tsx
Add DOMRenderer story to demo `unstable_filterCSSRule`.
> chore: Add DOMRenderer filter story

- README.md
+ License Header which is common in all Microsoft Project Repositories.
> Added a License Header to README.md.

- package.json
Add script to perform Typescript check on all affected packages.
```script
yarn type-check
```
> chore: add type-check script

- .yarn/patches/beachball-npm-2.21.0-85c8ba3d6b
- azure-pipelines.yml
- beachball.config.js
- beachball.hooks.js
- change/@griffel-jest-serializer-4e265c1c-2692-4b28-9842-f0408ff0cda9.json
- change/@griffel-webpack-loader-12eac84e-3865-42b8-926a-760952eec044.json
- packages/jest-serializer/project.json
- packages/webpack-loader/project.json
- yarn.lock
This PR fixes publishing with `beachball`, see comments on files themselves for details.
> chore: fix publishing with beachball

- azure-pipelines.compliance.yml
- azure-pipelines.yml
This PR adds new compliance checks required by security policies. They will run before the actual release.
> chore: add compliance checks

- change/@griffel-babel-preset-99d30eb2-d5e6-4809-8d5f-4bd74bd9b63f.json
- change/@griffel-webpack-loader-e2524be4-c006-472d-887b-75edb392d60b.json
- packages/babel-preset/README.md
- packages/webpack-loader/README.md
This PR updates README for `@griffel/webpack-loader` to include configuration guide for Webpack loader.
> docs: improve README for Webpack loader

- packages/devtools/.storybook/main.js
- packages/devtools/.storybook/preview-head.html
- packages/devtools/.storybook/tsconfig.json
- packages/devtools/README.md
- packages/devtools/project.json
- packages/devtools/src/index.html
- packages/devtools/src/stories/DefaultMessage.stories.tsx
- packages/devtools/src/useMakeStylesState.ts
- packages/devtools/tsconfig.json
- packages/devtools/tsconfig.lib.json
Add storybook for devtools components:
> chore: add Devtools storybook

- beachball.config.js
👆 to avoid useless change files for tests, stories, etc.
> chore: add "ignorePatterns" to beachball.config.js

- change/@griffel-core-e9730721-98ad-4971-8976-6f934c35cf1f.json
- packages/core/src/index.ts
- packages/core/src/shorthands/index.ts
- packages/core/src/shorthands/inset.test.ts
- packages/core/src/shorthands/inset.ts
- packages/core/src/shorthands/types.ts
> feat: adds inset shorthand

- change/@griffel-core-ad30b8f8-c6c7-481e-be0d-2e8268b29fdd.json
- packages/core/src/index.ts
- packages/core/src/shorthands/index.ts
- packages/core/src/shorthands/outline.test.ts
- packages/core/src/shorthands/outline.ts
- packages/core/src/shorthands/types.ts
> feat: add shorthand function for outline

- packages/devtools/src/SlotCSSRules.tsx
Clicking on slot name collapse/expand styles within:
> feat(devtools): click slot name collapse/expand styles within

- packages/react/src/renderToStyleElements.test.tsx
Add test for `renderToStyleElements` that runs in Jest DOM env.
> add test for renderToStyleElements()

- packages/devtools/project.json
Add package.json to build output so npm publish can work
> chore(devtools): add package.json to build output

- package.json
- yarn.lock
Final version of Docusaurus has been released -> bump the dependencies
> chore: bump docusaurus to 2.0.1

- apps/website/docs/react/api/shorthands.md
- change/@griffel-core-cca9a4d2-a460-4d77-a750-b6dd381c37f5.json
- packages/core/src/index.ts
- packages/core/src/shorthands/index.ts
- packages/core/src/shorthands/transition.test.ts
- packages/core/src/shorthands/transition.ts
- packages/core/src/shorthands/types.ts
- packages/react/README.md
> feat: adds transition shorthand

- apps/website/docs/react/guides/ssr-usage.md
Fixing a few minor typos found in the ssr-usage file.
> Addressing some minor typos within ssr-usage.md

- packages/react/src/createDOMRenderer.test.tsx
- packages/react/src/renderToStyleElements-node.test.tsx
- packages/react/src/renderToStyleElements.test.tsx
Fixes #246.
Surprisingly it just works as rules generated by `makeResetStyles` are just CSS rules and are inserted into the same bucket🗿
This PR adds tests to ensure that it will _continue_ to work.
> chore: add tests for hydration in makeResetStyles

- change/@griffel-react-3815ac0f-f221-4f2f-b4a6-0d1934fe6657.json
- packages/react/src/index.ts
This PR re-exports `GriffelResetStyle` in `@griffel/react`.
> feat: re-export GriffelResetStyle type

- apps/website/docs/react/guides/limitations.md
Improves docs based on feedback in #286.
> docs: Improve limitations page

- change/@griffel-core-e59b2cbc-4a06-4803-ac9b-c6ed34521758.json
- packages/core/src/renderer/getStyleSheetForBucket.ts
> fix: avoid mutations in getStyleSheetForBucket

- change/@griffel-core-ea61242a-f63f-4c81-ba59-b813d6ed5565.json
- packages/core/src/runtime/compileCSS.ts
- packages/core/src/runtime/resolveStyleRules.test.ts
- packages/core/src/runtime/resolveStyleRules.ts
> fix: do not emit "undefined" for CSS rules

- apps/website/docs/try-it-out/try-it-out.mdx
- apps/website/docusaurus.config.js
- apps/website/src/components/Playground/code/app.js
- apps/website/src/components/Playground/index.tsx
- package.json
- yarn.lock
> chore: bump @codesandbox/sandpack-react

- change/@griffel-webpack-extraction-plugin-571baa73-c908-4cab-ad28-73d69aaed382.json
- package.json
- packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
- yarn.lock
> chore: use typings for @babel/helper-module-imports

- .eslintrc.json
- change/@griffel-devtools-240ea0de-0d32-481f-8573-315857bcf791.json
- change/@griffel-webpack-extraction-plugin-84f522e8-cf92-477d-a545-572c97b0ab48.json
- packages/devtools/src/FlattenView.tsx
- packages/webpack-extraction-plugin/__fixtures__/webpack/reset-media/code.ts
- packages/webpack-extraction-plugin/__fixtures__/webpack/reset-media/fs.json
- packages/webpack-extraction-plugin/__fixtures__/webpack/reset-media/output.css
- packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
- packages/webpack-extraction-plugin/src/parseCSSRules.ts
- packages/webpack-extraction-plugin/src/sortCSSRules.ts
> fix: properly handle @media in __resetStyles()

- change/@griffel-core-ae7e2098-cbb1-4d62-816d-ee219e383612.json
- package.json
- packages/core/package.json
- yarn.lock
Bumps `rtl-css-js` to get https://github.com/kentcdodds/rtl-css-js/pull/69.
> chore: bump rtl-css-js

- apps/benchmark/src/implementations/merge-styles-v7/Box.tsx
- apps/benchmark/src/implementations/merge-styles-v7/Dot.tsx
- apps/benchmark/src/implementations/merge-styles-v7/Provider.tsx
- apps/benchmark/src/implementations/merge-styles-v7/View.tsx
- apps/benchmark/src/implementations/merge-styles-v7/index.ts
- apps/benchmark/src/implementations/types.ts
- package.json
- yarn.lock
Installs `@uifabric/merge-styles` to the repo and creates a new benchmark implementation
> chore: Adds benchmark for v7 merge-styles

- packages/eslint-plugin/README.md
The existing docs don't seem to work, I've updated them to what did work for our repo.
> Fix @griffel/eslint-plugin usage documentation

- .github/workflows/deploy.yml
Updates our deployment to use official actions from Github.
> chore: update deploy workflow

- apps/website/src/components/Playground/code/templates/animation.js
> docs: Add animation example to playground

- e2e/typescript/src/test.ts
> chore(e2e-ts): add newer versions of TypeScript

- change/@griffel-shadow-dom-5e958d15-5e5b-415a-88dc-4ce5d171ab18.json
- packages/core/src/renderer/getStyleSheetForBucket.test.ts
- packages/shadow-dom/src/createShadowDOMRenderer.test.ts
- packages/shadow-dom/src/createShadowDOMRenderer.ts
- packages/shadow-dom/src/findInsertionPoint.test.ts
- packages/shadow-dom/src/findInsertionPoint.ts
Fixes an issue sorting logic with `@media` queries in `@griffel/shadow-dom`. New test cases added.
> fix(shadow-dom): update sorting logic

- change/@griffel-core-4aed8fac-fc17-499c-8ecc-37b384c5d500.json
- packages/core/src/makeStyles.ts
- packages/core/src/runtime/resolveStyleRules.test.ts
- packages/core/src/runtime/resolveStyleRules.ts
- packages/core/src/runtime/utils/hashClassName.ts
- packages/core/src/runtime/utils/hashPropertyKey.test.ts
- packages/core/src/runtime/utils/hashPropertyKey.ts
Fixes #399. See https://github.com/microsoft/griffel/issues/399#issuecomment-1640927987 for explainer.
> fix(core): add container queries to hash generation

- packages/core/src/runtime/compileCSSRules.test.ts
> test(core): add tests for compileCSSRules

- apps/website/src/pages/index.module.css
> docs: add missing animation

- azure-pipelines.yml
Test Run: https://uifabric.visualstudio.com/UI%20Fabric/_build/results?buildId=324877&view=logs&j=bc38e8b8-e027-53cb-48e7-2adbd1070eca
> Enable 1ESPt for compliance

- change/@griffel-core-d6920882-00d0-4a0d-abc4-b1fa96fa2195.json
- packages/core/src/runtime/stylis/prefixerPlugin.test.ts
- packages/core/src/runtime/stylis/prefixerPlugin.ts
> feat(core): add prefixing for "backdrop-filter"

- change/@griffel-devtools-a62e678a-424d-48c1-a910-c370523a4977.json
- packages/devtools/src/sourceMap/sourceMapConsumer.ts
> chore: fix getOriginalPosition() to work in Storybook

- yarn.lock
Bumps `ip` to resolve security alert.
> chore: bump nodegyp & ip

- change/@griffel-postcss-syntax-a2eb1030-cce7-4de3-bb90-b3f4c9a03a52.json
- packages/postcss-syntax/src/stringify.ts
> fix: Remove console.log

- change/@griffel-style-types-f154bb98-0961-405f-ae62-cc5beb9eff4f.json
- packages/core/src/shorthands/types.test.ts
- packages/style-types/src/makeStyles.ts
- packages/style-types/src/shared.ts
> fix(style-types): use custom fallback type

- change/@griffel-core-b3e9ee3c-93d4-4c80-ab9a-6effc12045ee.json
- packages/core/src/common/snapshotSerializers.ts
- packages/core/src/makeResetStyles.test.ts
- packages/core/src/makeStaticStyles.test.ts
- packages/core/src/makeStyles.test.ts
- packages/core/src/renderer/createDOMRenderer.test.ts
Updates `griffelRendererSerializer` to emit `{"data-priority"}` in snapshots.
> chore: update serializer

- change/@griffel-tag-processor-ad573e7a-dde2-4257-b0a4-61baf16d7b9f.json
- packages/tag-processor/src/MakeStylesProcessor.ts
- packages/vite-plugin/__fixtures__/object/code.ts
- packages/vite-plugin/__fixtures__/object/output.ts
- packages/vite-plugin/project.json
> fix(tar-processor): fix handling of meta

- change/@griffel-jest-serializer-4d8d3102-ee2f-4b0f-bd12-6447c2e066ea.json
- packages/jest-serializer/src/index.test.tsx
- packages/jest-serializer/src/index.ts
> fix(jest-serializer): fix space handling & false positives

- apps/website/docs/react/api/create-dom-renderer.md
- change/@griffel-core-6d8b0e4c-e53b-469f-aff5-fbc1505643d5.json
- packages/core/src/makeResetStyles.test.ts
- packages/core/src/makeResetStyles.ts
- packages/core/src/makeStyles.test.ts
- packages/core/src/makeStyles.ts
- packages/core/src/renderer/createDOMRenderer.ts
- packages/core/src/types.ts
> feat(core): add "classNameHashSalt" option

- change/@griffel-style-types-575e2e50-6a33-4809-92fe-5397857895d4.json
- packages/style-types/src/makeStaticStyles.ts
> Add font-display to @font-face in makeStaticStyles type

- yarn.lock
> chore: bump express

- change/@griffel-core-34ce2cd1-533d-4dff-bc68-5459e76de7e5.json
- packages/core/src/devtools/injectDevTools.ts
> fix: remove early return

- .github/workflows/bundle-size-baseline.yml
- .github/workflows/bundle-size-comment.yml
- .github/workflows/bundle-size-pr.yml
- .github/workflows/ci-change.yml
- .github/workflows/ci.yml
- .github/workflows/deploy.yml
- .github/workflows/extension.yml
Pins GH actions to hashes per GH recommendations.
> chore: pin GH actions to hashes
