microsoft/griffel

.browserslistrc
bundle-size.config.js
package.json
packages/core/.babelrc
packages/core/bundle-size/makeStyles.fixture.js
packages/core/package.json
packages/core/project.json
yarn.lock

This PR:
- adds `.browserslistrc` config to be used with `@babel/preset-env`
- adds `@fluentui/bundle-size` tool and the first fixture for `@griffel/core`
- adds `babel-plugin-annotate-pure-calls` and enables it
- adds `sideEffects: false` to `packages/core/package.json` to enable tree-shaking

chore: init bundle size tool, add "sideEffects": false & Babel plugin

---

.yarn/patches/beachball-npm-2.20.0-a05e0aaaff
beachball.config.js
package.json
yarn.lock

This PR adds [`beachball`](https://www.npmjs.com/package/beachball) as the releasing tool.
The included patch allows to use build output from NX.

chore: init beachball

---

change/@griffel-core-2a8ca2c5-72f7-4897-bf39-77720651d3cc.json
packages/core/src/__styles.ts
packages/core/src/common/snapshotSerializers.ts
packages/core/src/index.ts
packages/core/src/makeStaticStyles.test.ts
packages/core/src/makeStaticStyles.ts
packages/core/src/makeStyles.test.ts
packages/core/src/makeStyles.ts
packages/core/src/mergeClasses.test.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/renderer/rehydrateRendererCache.ts
packages/core/src/resolveStyleRulesForSlots.ts
packages/core/src/runtime/compileKeyframeCSS.test.ts
packages/core/src/runtime/compileKeyframeCSS.ts
packages/core/src/runtime/compileStaticCSS.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/utils/cssifyObject.ts
packages/core/src/types.test.ts
packages/core/src/types.ts

This PR renames types that had wrong names during initial push:
- `GriffelStaticStylesStyle` => `GriffelStaticStyle`
-  `GriffelStylesAnimation` => `GriffelAnimation`
-  `GriffelStylesStyle` => `GriffelStyle`
- `GriffelStaticStylesOptions` => `MakeStaticStylesOptions`
- `GriffelStylesOptions` => `MakeStylesOptions`
- `GriffelStylesRenderer` => `GriffelRenderer`

fix: rename types to proper names

---

change/@griffel-core-ae835232-8a2a-48df-a1d2-6a524f897338.json
packages/core/src/mergeClasses.ts

This PR fixes a bug with false positive warning, the regression was introduced in https://github.com/microsoft/fluentui/pull/21288.
The warning should be emitted only when `DEFINITION_LOOKUP_TABLE[sequenceId]` does not exist. But existing condition also triggered it when `sequencesIds[i]` is `undefined` while `sequencesIds[i]` can be `undefined`, it's okay.

fix false positive warning in mergeClasses()

---

.eslintrc.json
.github/workflows/ci.yml
change/@griffel-react-158feffa-02ae-4f23-b7a9-ad115833d5a8.json
packages/react/src/RendererContext.tsx
packages/react/src/makeStaticStyles.ts

This PR enables `lint` command (or target in terms of NX) in CI pipelines.
Don't know how I overlooked it initially.

chore: enable "lint" in CI checks

---

.yarn/patches/@nrwl-workspace-npm-13.4.5-233a3ec85c
workspace.json
yarn.lock

- Adds NX patch to workaround nrwl/nx#8322, patches are tracked in #15
- Renames packages in workspace as @Hotell suggested. It's not a big problem, but adds confusion in Nx configs:
```json
{ "implicitDependencies": ["react"] }
```
_vs._
```json
{ "implicitDependencies": ["@griffel/react"] }
```

chore: add NX patch to fix "implicitDependencies", rename workspaces

---

change/@griffel-webpack-loader-9ea1134d-1b02-4967-a5da-2225b4669f1d.json
packages/webpack-loader/src/webpackLoader.ts

Loaders in Webpack are cacheable by default (https://webpack.js.org/api/loaders/#thiscacheable). But in there edge cases/bugs when caching does not work until it's specified (https://github.com/webpack/webpack/issues/14946).
This PR unblocks integration to the product.
| Test                       |      Time |
| -------------------------- | --------: |
| With`this.cacheable()`     |   28038ms |
| Without `this.cacheable()` | 222428 ms |
Without `this.cacheable()` Webpack always shows the same times as a cold start.

fix(webpack-loader): use this.cacheable() to improve performance

---

change/@griffel-core-71ab0a7a-1391-4c59-9712-7048e84fa2b5.json
change/@griffel-react-da0ae3ee-1d28-4610-a9e1-d2decfba295a.json
tools/getRollupOptions.js

Fixes #34.
The problem affects only packages bundled for web (`@griffel/core` & `@griffel/react`). This PR adds sourcemaps for these packages:
_It seems that `@nrwl/web:rollup` does not generate sourcemaps and it's not configurable (while it's just the Rollup option). I will trigger an issue for them if it's true._

chore: output sourcemaps with Rollup

---

.github/workflows/ci-change.yml
packages/babel-preset/src/schema.ts

`depth: 0` is a required setting to make the command working properly: https://github.com/microsoft/beachball/blob/7491719208b66de6d1c5131e0f1eeb5203807499/.github/workflows/pr.yml#L21-L22

chore: fix "change" workflow

---

.github/workflows/ci.yml
apps/website/project.json
change/@griffel-babel-preset-ade2cc60-0637-4df7-a5f6-4697bfc5397d.json
change/@griffel-core-7c61bf65-d1cd-439b-8a52-173551bad483.json
change/@griffel-jest-serializer-9655a39c-cd7c-4675-97e1-0e531f048be4.json
change/@griffel-react-2d4f8065-f777-4025-aa0a-f0ebbf63c697.json
change/@griffel-webpack-loader-f6e64b6c-4bfd-47fe-acfb-a84c769ae14a.json
nx.json
packages/babel-preset/__fixtures__/object-sequence-expr/code.ts
packages/babel-preset/__fixtures__/object-sequence-expr/output.ts
packages/babel-preset/project.json
packages/babel-preset/tsconfig.spec.json
packages/core/project.json
packages/jest-serializer/project.json
packages/react/.storybook/tsconfig.json
packages/react/project.json
packages/webpack-loader/project.json
packages/webpack-loader/tsconfig.spec.json

This PR implements new Nx target called `type-check` to have proper checks for TypeScript.
Motivation:
- broken type checks during build, https://github.com/nrwl/nx/issues/9053
- broken type checks in fixtures, for example `packages/babel-preset/__fixtures__/object-sequence-expr/output.ts` in this PR

chore: add proper type checking

---

tools/getRollupOptions.js

> Do not touch things if they work
> Controls how Rollup handles default, namespace and dynamic imports from external dependencies in formats like CommonJS that do not natively support these concepts.
> https://rollupjs.org/guide/en/#outputinterop
This PR enables it back. It affects only CommonJS output and is required to work properly.

fix: enable interop back in Rollup

---

.storybook/main.js

Use `@babel/typescript` to compile typescript in storybook.
`@nrwl/react/babel` transpiles the code too much (`for..in` transpiled to a function). That makes the code different to what we ship and also more difficult to debug.

chore(storybook): Use @babel/typescript

---

change/@griffel-babel-preset-66cba623-8b9a-422f-ba36-22ad7d7ebc69.json
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts

This PR removes implicit dependency on `@babel/preset-typescript` for module evaluation.
If it's used - it should be specified obviously.

fix(babel-preset): remove implicit dependency on TypeScript preset

---

.github/workflows/deploy.yml

Adds `CNAME` file generation.
References:
- https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-add-cname-file-cname

chore: add CNAME generation on deploy

---

.github/workflows/ci-change.yml
.github/workflows/ci.yml
change/@griffel-core-9687dcfc-600f-454e-8ae6-cd1267200313.json
e2e/typescript/src/assets/fixture.ts
e2e/typescript/src/test.mjs
packages/core/src/types.ts

Fixes #49.
Changes are based on TypeScript behavior:
```ts
type A = { foo: number } | { [P: string]: string}
type B = { foo: number } & { [P: string]: string}
// ✅ Passing
const a: A = { foo: 1, bar: 'bar' }
// 🔴 "Type '{ foo: number; bar: string; }' is not assignable to type 'B'."
const b: B = { foo: 1, bar: 'bar' }
```
[TypeScript playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAglC8UDeUBmB7dAuKA7ArgLYBGEATlAL5QA+yUA2gAo4DOwZAlrgOYC6bDtx6UAUKEhQAQgnoZseIqQrUAZPWaCuvAVHbaRo0QGN0udlACGOOIhTycARgA0UYpbI4A5O7JeqJmYWxDgydmiYTq6+3r7+YoHm6AA2EAB0yeg8ABSW0QCUokA)

fix: improve typings to solve TS issues

---

change/@griffel-webpack-loader-532ba64d-8c9e-4cad-a26f-32c1ac51dcb8.json
package.json
yarn.lock

As we had `@babel/core` in `devDependencies` & in `dependencies` in root `package.json` Nx was confused and didn't add `@babel/core` to dependencies of packages.
This affected release of `@griffel/webpack-loader@2.0.1`.

fix: update dependencies of Webpack loader

---

.eslintrc.json
.github/workflows/ci.yml
change/@griffel-babel-preset-e46a4792-94be-4d91-a320-8385a6e87e90.json
change/@griffel-core-fa84ecb8-c2e6-4a70-b091-c7ce4d52b97a.json
change/@griffel-jest-serializer-195cd5ed-09a1-4465-b408-baf1527a1ec9.json
change/@griffel-react-700de188-ed33-42a1-a65f-025b0584f342.json
change/@griffel-webpack-loader-201e829c-6c79-4c21-a383-2362f234dc8a.json
package.json
packages/babel-preset/package.json
packages/core/.eslintrc.json
packages/core/package.json
packages/jest-serializer/package.json
packages/react/package.json
packages/webpack-loader/package.json
yarn.lock

This PR:
- adds dependencies for each package explicitly, this allows `beachball` (releasing tool) to properly populate & bump dependencies
- to ensure that all dependencies are declared I added `import/no-extraneous-dependencies`:
- to ensure that dependencies are in sync I added `syncpack` check

chore: add explicit dependencies

---

package.json

A follow up for #66.
- use correct command for checking
- use long flags to make it clearer

chore: fix script check-dependencies script

---

azure-pipelines.yml

Before I used personal temporary NPM token for releasing. This is not good 😈
We have solved difficulties and can use proper tokens now.

chore: use proper NPM token

---

apps/website/docs/react/api/create-dom-renderer.md
change/@griffel-core-f0caf7c5-b487-47b5-8dbb-7f23f433c325.json
change/@griffel-react-91a6f79f-816d-4ac0-8d0a-58fa0719a7d3.json
packages/core/src/renderer/createDOMRenderer.test.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/react/README.md

Fixes #75.
This PR adds `styleElementAttributes` to `createDOMRenderer()`. `styleElementAttributes` is a map of attributes that's passed to the generated style elements. For example, is useful to set ["nonce" attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce).
```js
import { createDOMRenderer } from '@griffel/react';
const renderer = createDOMRenderer(targetDocument, {
styleElementAttributes: {
nonce: 'random',
},
});
```

feat: add "styleElementAttributes" to createDOMRenderer

---

change/@griffel-babel-preset-893a7a76-6351-4d7d-95f0-4f85fc59cb2b.json
packages/babel-preset/README.md
packages/babel-preset/src/index.ts

This PR re-exports the evaluator from `@linaria/shaker` and updates README file for `@griffel/babel-preset`.
We had the same experience with both existing internal customers of Webpack loader - it's required to tweak evaluation settings. For that we need to configure the evaluator, but it's not re-exported we need to add a dependency to third party module and update it separately 😯

feat: export shaker evaluator

---

change/@griffel-react-82e46cbc-d83a-4acd-89ff-4278e1eb9b1e.json
packages/react/src/makeStyles.ts

Fixes #89.
This PR fixes a warning (see the issue for details) by checking if React's dispatcher is present. While this approach uses `__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED` it works consistently with all versions of React.
See, https://github.com/microsoft/griffel/issues/89#issuecomment-1086589073.
- React 16.8 https://codesandbox.io/s/focused-fast-01v7xq?file=/src/App.js
- React 17 https://codesandbox.io/s/musing-sunset-d3k6rl?file=/src/App.js
- React 18 https://codesandbox.io/s/twilight-hill-8biwip?file=/src/App.js

fix: avoid errors with React 18

---

package.json

Without this change `beachball` fails to properly detect remote and has false positive results `yarn change` because of that.

chore: fix beachball remote

---

change/@griffel-babel-preset-9f9b43ef-1aa0-45c0-ba63-27be317357d3.json
change/@griffel-webpack-loader-6a8b470c-f154-43cc-aebb-08c5a47e124d.json
packages/babel-preset/src/index.ts
packages/webpack-loader/package.json
packages/webpack-loader/src/webpackLoader.ts

Both `@griffel/babel-preset` & `@griffel/webpack-loader` depend on `@linaria/babel-preset`. There should be nothing wrong with that, but Yarn v1 does not hoist dependencies to root `node_modules`.
```
/node_modules
/@linaria/babel-preset
/@griffel/babel-preset
/@griffel/webpack-loader
```
```
/node_modules
/@griffel/babel-preset
/@linaria/babel-preset
/@griffel/webpack-loader
/@linaria/babel-preset
```
As module resolution is injected as a static property this causes hard to catch bugs.
https://github.com/microsoft/griffel/blob/01e52783012cb38d91b474858419d417b6c46410/packages/webpack-loader/src/webpackLoader.ts#L88-L92
Example of the issue: https://github.com/microsoft/fluentui/pull/21976#discussion_r843964679

chore: export "EvalCache" & "Module" from @griffel/babel-preset

---

change/@griffel-core-8a3b4de2-ff52-4c79-aa40-84cdf0bb669e.json
change/@griffel-eslint-plugin-0f2d3131-9acc-46f2-b1a1-b7c23c1e852a.json
package.json
packages/core/src/index.ts
packages/eslint-plugin/.babelrc
packages/eslint-plugin/.eslintrc.json
packages/eslint-plugin/README.md
packages/eslint-plugin/jest.config.js
packages/eslint-plugin/package.json
packages/eslint-plugin/project.json
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/no-shorthands.md
packages/eslint-plugin/src/rules/no-shorthands.test.ts
packages/eslint-plugin/src/rules/no-shorthands.ts
packages/eslint-plugin/src/utils/createRule.ts
packages/eslint-plugin/src/utils/helpers.ts
packages/eslint-plugin/tsconfig.json
packages/eslint-plugin/tsconfig.lib.json
packages/eslint-plugin/tsconfig.spec.json
tsconfig.base.json
workspace.json
yarn.lock

This PR adds `@griffel/eslint-plugin` with a single ESLint rule to enforce usage of CSS longhands.
Fixes #76.
Griffel does not support usage of CSS shorthands, [microsoft/griffel#30](https://github.com/microsoft/griffel/issues/30#issuecomment-1045959297).
This is enforced by typings, but there are cases when they don't work as expected [microsoft/griffel#78](https://github.com/microsoft/griffel/issues/78).
Examples of **incorrect** code for this rule:
```js
import { makeStyles } from '@griffel/react';
export const useStyles = makeStyles({
root: {
background: 'red',
padding: '10px 20px',
},
});
```
Examples of **correct** code for this rule:
```js
import { makeStyles } from '@griffel/react';
export const useStyles = makeStyles({
root: {
backgroundColor: 'red',
...shorthands.padding('10px', …
```

feat: create ESLint plugin for Griffel

---

change/@griffel-babel-preset-41b92af0-6e5b-4e53-b341-0bd5b8407b76.json
packages/babel-preset/__fixtures__/duplicated-imports/code.ts
packages/babel-preset/__fixtures__/duplicated-imports/options.json
packages/babel-preset/__fixtures__/duplicated-imports/output.ts
packages/babel-preset/src/transformPlugin.ts

Currently, the transform plugin only keeps tab of the last import statement where the package name (`moduleSource`) is a match. For example, in:
```javascript
import { dupImport1 } from 'custom-package';
import { createStyles } from 'custom-package';
import { dupImport2 } from 'another-custom-package';
import { otherImport } from 'another-package';
```
with config:
```javascript
{
"modules": [
{ "moduleSource": "custom-package", "importName": "createStyles" },
{ "moduleSource": "another-custom-package", "importName": "createMyStyles" }
]
}
```
The plugin will only focus on the 3rd import line (`import { dupImport2 } from 'another-custom-package';`) and then decide that there's no placement needed, thus missing the 2nd import where `createStyles` actually exists.
This PR fixes this issue …

Fix transform plugin so it can handle more than one matched import sources

---

packages/devtools/package.json
packages/devtools/src/FlattenView.tsx
packages/devtools/src/MonolithicRulesView.tsx
packages/devtools/src/RulesView.tsx
packages/devtools/src/SlotCSSRules.tsx
packages/devtools/src/ViewContext.ts
packages/devtools/src/getMonolithicCSSRules.test.ts
packages/devtools/src/getMonolithicCSSRules.ts
packages/devtools/src/index.tsx
packages/devtools/src/stories/FlattenView.stories.tsx
packages/devtools/src/types.ts
packages/devtools/src/utils.test.ts
packages/devtools/src/utils.ts

Add real UI for griffel devtools.
- show all makeStyles calls with slot name and monolithic css rules
- atomic css rules from devtools result are processed into monolithic css objects using `stylis`
- displayed overridden css rules; clicking on them highlights the overriding rules
TODOs on devtools UI
- Show code highlights for css rules
- Add search function
- Click slot name expand/collapse rules within
- Show className for each rule
- Collapse shorthands in devtools UI
TODOs on devtools data:
- currently devtools is always disabled from @griffel/core, find out a way to enable it that is compatible with SSR
- Add sourcemap to devtools data; jump to source code from devtools UI

feat(Devtools): UI to display monolithic css rules per makeStyle slot 

---

change/@griffel-core-94a0ec59-abfa-4d0f-a8a8-843026c57848.json
packages/core/src/runtime/compileCSS.ts
packages/core/src/runtime/resolveStyleRules.test.ts

Fixes #105 
When writing styles with multiple selectors and rules that will be flipped for RTL only the first selector is properly scoped to the generated class name.
```js
import { makeStyles } from '@griffel/core';
export default makeStyles({
root: {
':active,:focus-within': {
paddingLeft: '10px'
}
},
});
```
Generates
```
.f14f5aie:active,
.f14f5aie:focus-within {
padding-left: 10px;
}
.f1sheuf0:active,
// 💣💥`:focus-with` rule applies globally! 😱
:focus-within {
padding-right: 10px;
}
```
```js
import { makeStyles } from '@griffel/core';
export default makeStyles({
root: {
':active,:focus-within': {
paddingLeft: '10px'
}
},
});
```
Generates
```
.f14f5aie:active,
.f14f5aie:focus-within {
padding-left: 10px;
}
.f1sheuf0:active,
// `:focus-within` is properly scoped 👍👍 …
```

Fix: Multiple selectors and RTL flipping

---

apps/website/docs/react/api/create-dom-renderer.md
apps/website/docs/react/api/make-static-styles.md
apps/website/docs/react/api/shorthands.md
apps/website/docs/react/guides/atomic-css.md
apps/website/docs/react/guides/build-time-transforms.md
apps/website/docs/react/guides/limitations.md
apps/website/docs/react/guides/ssr-usage.md
change/@griffel-core-cbfaaa86-8f9f-4b6d-bbbc-97a91bc628f3.json
change/@griffel-react-bdfe2a55-bc15-43bf-8c29-e63d7ac1b1d5.json
packages/core/README.md
packages/react/README.md

Fixes #30.
This PR:
- adds new page to website about `shorthands` & section to README
- adds limitations page that describes why CSS shorthands are forbidden
- minor improvements

docs: add limitations & shorthands, minor improvements

---

change/@griffel-core-8e16f578-f749-4f26-9899-b90b14811104.json
packages/core/jest.config.js
packages/core/src/devtools/isDevToolsEnabled.ts
packages/devtools/public/content-script.js
packages/devtools/public/manifest.json

When griffel devtools start, content-script.js will run and add `__GRIFFEL_DEVTOOLS__` as `enabled` in sessionStorage.
Griffel core can use it to determine if devtools should be injected.
Reason for `sessionStorage`: content script runs in an isolated world. Changes like `document.XXX = yyy` in content script will not be reflected on the page (page will still have `document.XXX = undefined`)

feat(Devtools): enable it via content_scripts

---

packages/devtools/src/SlotCSSRules.tsx

When click on slotName to expand/collapse styles within, show triangle indicator:

feat(devtools): Add triangle right indicator for collapsed slot

---

change/@griffel-core-fc0dd800-dab6-437c-8222-72f89351fdf8.json
packages/core/src/devtools/isDevToolsEnabled.ts

There are two issues with the existing check:
- it's not properly tree shaken with `webpack@4` & `terser-webpack-plugin@4`
- it throws in incognito mode & with blocked third party cookies
```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
at http://192.168.0.150:3000/iframe:18:28
at http://192.168.0.150:3000/iframe:25:9
```

fix: update isDevToolsEnabled check

---

change/@griffel-react-1edea5c5-031f-429a-b073-dbb1396fdb96.json
packages/react/src/RendererContext.tsx
packages/react/src/index.ts

This PR exports `useRenderer_unstable`, current instance of `GriffelRenderer` can be obtained from it.
⚠️ **It's unstable & undocumented API, use it on own risk.**

feat: export useRenderer_unstable

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.gitignore

Adds `devcontainer` base configuration file to allow [Developing inside a Container](https://code.visualstudio.com/docs/remote/containers) with Docker at vscode.
Might need to add extra configuration on Dockerfile to ensure e2e tests with cypress

feat: adds devcontainer for vscode

---

packages/webpack-extraction-plugin/__fixtures__/babel/basic/code.ts
packages/webpack-extraction-plugin/__fixtures__/babel/basic/output.ts
packages/webpack-extraction-plugin/__fixtures__/babel/multiple/code.ts
packages/webpack-extraction-plugin/__fixtures__/babel/multiple/output.ts
packages/webpack-extraction-plugin/package.json
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.test.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/tsconfig.lib.json
packages/webpack-extraction-plugin/tsconfig.spec.json

This PR implements the Babel plugin that will be used for CSS extraction.
This plugin replaces `__styles` with `__css` function and removes CSS rules from output:
```tsx
import { __styles } from '@griffel/react';
export const stylesA = __styles(
{
root: {
sj55zd: 'fe3e8s9',
},
},
{
d: ['.fe3e8s9{color:red;}'],
},
);
export const stylesB = __styles(
{
root: {
De3pzq: 'fcnqdeg',
},
},
{
d: ['.fcnqdeg{background-color:green;}'],
},
);
//
// ⬇️⬇️⬇️
//
import { __styles, __css } from '@griffel/react';
export const stylesA = __css({
root: {
sj55zd: 'fe3e8s9',
},
});
export const stylesB = __css({
root: {
De3pzq: 'fcnqdeg',
},
});
```
CSS rules are returned as part of `meta` informantion.

feat: add Babel plugin for CSS extraction

---

packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.ts
packages/webpack-extraction-plugin/package.json
packages/webpack-extraction-plugin/project.json
packages/webpack-extraction-plugin/src/schema.ts
packages/webpack-extraction-plugin/src/transformSync.ts
packages/webpack-extraction-plugin/src/webpackLoader.test.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts
packages/webpack-extraction-plugin/tsconfig.json
packages/webpack-extraction-plugin/tsconfig.lib.json
packages/webpack-extraction-plugin/virtual-loader/griffel.css
packages/webpack-extraction-plugin/virtual-loader/index.js

This PR adds a Webpack loader that invokes Babel plugin (#135) and performs CSS extraction.
P.S. The next PR will contain a Webpack plugin to concatenate and deduplicate rules.

feat: add Webpack plugin for CSS extraction

---

packages/webpack-extraction-plugin/src/webpackLoader.test.ts

Fixes the flacky tests from #139.

chore: increase timeouts for tests in webpack-extraction-plugin

---

change/@griffel-core-4ea31e7f-39dc-486b-8a22-3545f609a5cb.json
change/@griffel-react-8818a204-4697-4df6-8848-771f49c2bfdb.json
packages/core/src/__css.ts
packages/core/src/index.ts
packages/react/bundle-size/__css.fixture.js
packages/react/bundle-size/__styles.fixture.js
packages/react/src/__css.ts
packages/react/src/index.ts

This PR adds new `__css` functions to `@griffel/core` & `@griffel/react`.
The difference to existing `__styles` is that the part related to CSS insertion is completely stripped.

chore: add __css() functions for upcoming CSS extraction

---

packages/devtools/package.json
packages/devtools/src/FlattenView.tsx
packages/devtools/src/getMonolithicCSSRules.test.ts
packages/devtools/src/getMonolithicCSSRules.ts
packages/devtools/src/stories/FlattenView.stories.tsx

- fix key: previously slot name was used as key for `SlotCSSRules` component but slot name can be the same and causing issue
- make input bar stick to top
- fix parsing of css rule selector when the rules are like `[data-key-nav] .fxxxx{color:red}`. 
Before: 
After:

feat(devtools): fix duplicated key + make input stick to top + fix [data-key-nav] selector

---

change/@griffel-core-136e2d80-22ac-475b-b95d-7608a762fa81.json
packages/core/src/index.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/runtime/getStyleBucketName.ts
packages/core/src/runtime/reduceToClassNameForSlots.ts
packages/core/src/runtime/utils/normalizeCSSBucketEntry.ts
packages/core/src/types.ts
packages/webpack-extraction-plugin/.eslintrc.json
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/rules-deduplication/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/rules-deduplication/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/rules-deduplication/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/style-buckets/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/style-buckets/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/style-buckets/output.css
packages/webpack-extraction-plugin/package.json
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

This PR is the last one to support CSS extraction.
The PR:
- add sorting of CSS rules and implements the same logic as #141 with Stylis
- adds new fixtures and tests
- cleanup `@internal` modifiers and adds necessary exports from `@griffel/core`

feat: add CSS extraction

---

change/@griffel-webpack-extraction-plugin-2264cf3b-bf8b-4a75-b908-a443cccfca4e.json
packages/core/src/runtime/resolveStyleRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

This PR fixes handling of multiple CSS rules inside `element.children` for `getElementReference()`. This happens for cases when Griffel emits rules that flip in RTL.
```css
@media screen and (max-width: 992px) {
.f1f6067w {
text-align: left;
}
.f133ge8t {
text-align: right;
}
}
```

fix(webpack-extraction-plugin): improve getElementReference() to handle multiple children

---

change/@griffel-react-d55dcfa4-30d9-446f-9472-ae032925fbe4.json
packages/react/src/index.ts

Useful to export this type for users that want to declare options for `createDOMRenderer` outside of the actual function call
```ts
const options: CreateDOMRendererOptions = {
compareMediaQueries: (a, b) => a < b;
}
createDOMRenderer(document, options)
```

fix: export `CreateDOMRendererOptions` from `@griffel/react`

---

change/@griffel-webpack-extraction-plugin-9caf7232-4d9e-47bf-8052-2361d62a3790.json
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

Fixes #160.
When Webpack emits assets it can add a comment to source if [`output.pathinfo`](https://webpack.js.org/configuration/output/#outputpathinfo) is enabled. This PR strips all top-level comments as there is no sense in them - they cannot be sorted in output anyway.

fix(webpack-extraction-plugin): handle comments in output

---

apps/website/docs/try-it-out/try-it-out.mdx
apps/website/docusaurus.config.js
apps/website/sidebars.js
apps/website/src/components/OutputTitle/index.tsx
apps/website/src/components/Playground/code/app.js
apps/website/src/components/Playground/code/styles.js
apps/website/src/components/Playground/code/templates/border.js
apps/website/src/components/Playground/code/templates/global.js
apps/website/src/components/Playground/code/templates/margin.js
apps/website/src/components/Playground/code/templates/media.js
apps/website/src/components/Playground/code/templates/nested.js
apps/website/src/components/Playground/code/templates/padding.js
apps/website/src/components/Playground/code/templates/pseudo-elements.js
apps/website/src/components/Playground/code/templates/pseudo-selectors.js
apps/website/src/components/Playground/code/templates/selectors.js
apps/website/src/components/Playground/docusaurusPlugin.js
apps/website/src/components/Playground/index.tsx
apps/website/src/components/Playground/webpackLoader.js

This PR implements fixes and enhancements for docs.
After recent changes we have a strange output:
Before templates in playground were ordered based on names, not based on usage/complexity. This led to confusion as "Global selector" goes before actual "Selectors"...
Our templates had utility information that is redundant for users, now it's gone.

docs: improve try out experience

---

change/@griffel-core-2d973eb8-c6f3-4e30-882c-2590b8ff4e1b.json
change/@griffel-devtools-afaa43f6-11f2-4c19-a3bf-a8f6ce282256.json
packages/core/src/devtools/store.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/rehydrateRendererCache.ts
packages/devtools/src/utils.ts

This PR fixes https://github.com/microsoft/griffel/issues/173.

fix: add css rules to devtools extension debugger when pass renderer on SSR

---

change/@griffel-core-c60d0c4f-e496-4ec4-bb67-fae7384bfbe1.json
package.json
packages/core/package.json
packages/core/src/runtime/resolveStyleRules.test.ts
yarn.lock

**What**
Allow RTL flipping of CSS properties even if they reference CSS variables.
```js
boxShadow: '6px 3px 8px 5px var(--css-variable)';
/* ⬇️ now flips offset-x in RTL ⬇️ */
boxShadow: '-6px 3px 8px 5px var(--css-variable)';
```
**Why**
Previously, CSS properties which contained `var()` were not flipped.
There are cases where, when a CSS variable is used, there is no way how the value can be flipped:
```js
padding: 'var(--foo)'; /* 🔴 No way how to flip - foo can be a single value as well as four? */
```
On the other hand, there are other use cases, where the flipping is possible and meaningful:
```js
padding: margin: '1px var(--token) 3px 4px'; /* ✅ should be flipped to '1px 4px 3px var(--token)' */
boxShadow: '6px 3px 8px 5px var(--css-variable);' /* ✅ CSS variable used only for …
```

Fix(RTL): Flip CSS properties even if they contain CSS variables

---

change/@griffel-react-dec49600-8627-49d4-8e4d-a37852ccb6b6.json
packages/react/src/index.ts

`GriffelRenderer` type is needed to defined proper custom types to be used in Next.js (see https://github.com/microsoft/fluentui/issues/24158, https://github.com/microsoft/fluentui/pull/24202).

feat: re-export GriffelRenderer from @griffel/react

---

change/@griffel-babel-preset-14fc786d-9abc-48b0-a6f7-c9003426f5e9.json
package.json
packages/babel-preset/package.json
yarn.lock

Related to #195. Bumps `@linaria/babel-preset` to get https://github.com/callstack/linaria/pull/1046 and fix issues with imported helpers by SWC.

chore: bump @linaria/babel-preset for compatibility with Next.js

---

packages/next-extraction-plugin/README.md
packages/webpack-loader/README.md

This PR updates README files based on feedback from #190.

docs: update READMEs for next-extraction-plugin & webpack-loader

---

packages/core/src/runtime/resolveStyleRules.test.ts

This PR adds a test to ensure that `:hover` & `&:hover` handled equally and will work in consistently in style overrides.

test: add a test to ensure that "&" is handled equally

---

change/@griffel-devtools-32883921-647e-4e71-8659-54152995e3e5.json
packages/devtools/src/sourceMap/loadOriginalSourceLoc.ts

Devtools read source url from error stack. Sometimes these urls contain relative path, depending on how the app is bundled. However chrome always store resources using absolute path. This PR normalizes the source url so we can find it and read it using chrome resources API.

fix(devtools): normalize relative path in source url

---

change/@griffel-core-7e21a596-c13f-4428-a875-d535f075b2c3.json
packages/core/src/makeStyles.test.ts
packages/core/src/runtime/reduceToClassNameForSlots.ts

There are cases when a style set is [empty intentionally](https://github.com/microsoft/fluentui/blob/21af8da1d98c070a682b26b7d56775d43a749b3d/packages/react-components/react-button/src/components/Button/useButtonStyles.ts#L122-L124):
```ts
makeStyles({
root: { /* no rules */ },
})
```
This PR fixes the implementation to not emit a class in such cases to avoid it in DOM & useless class merging if it's passed to `mergeClasses()`.

fix: do not emit sequence hashes for empty sets

---

change/@griffel-core-7824828a-f980-4c5d-ba33-06d73ffb351d.json
change/@griffel-devtools-dcd68b39-8976-4d6a-9d04-5aa2e794d090.json
packages/core/src/devtools/getDebugTree.test.ts
packages/core/src/devtools/getDebugTree.ts
packages/core/src/devtools/store.test.ts
packages/core/src/devtools/utils.test.ts
packages/core/src/devtools/utils.ts
packages/devtools/src/MonolithicRulesView.tsx
packages/devtools/src/getMonolithicCSSRules.test.ts
packages/devtools/src/getMonolithicCSSRules.ts
packages/devtools/src/utils.test.ts
packages/devtools/src/utils.ts

Here's an example showing both problems: (using devtools on fluent v9 button component):
- Problem 1: when overriding rule is the same rule, devtools is not able to determine the overridng rule.
In the above example, 'medium' and the 'primary' slot contains the same style for focus. The one in 'medium' overrides the one in 'primary'. But devtools failed to detect it.
- Problem 2: when selector contains className like `.fxxxx.yyyy` where `.fxxxx` is the className used by griffel, devtools failed to parse this className
After this PR, both problems are fixed. 
Additionally, when clicking on a style, devtools highlights the overriding style. But in the case of problem 1 where both styles are the same, this highlighting feature highlights both styles (because they have the same griffel …

fix(devtools): show override when overriding rule is the same

---

change/@griffel-core-7e54114a-1960-4f4b-8fa5-2ac00bc9b673.json
change/@griffel-webpack-extraction-plugin-c462c63b-aec2-416d-a448-8006eee784c5.json
packages/core/src/runtime/compileCSS.test.ts
packages/core/src/runtime/compileCSS.ts
packages/core/src/runtime/getStyleBucketName.test.ts
packages/core/src/runtime/getStyleBucketName.ts
packages/core/src/runtime/resolveStyleRules.test.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/utils/hashClassName.ts
packages/core/src/runtime/utils/hashPropertyKey.test.ts
packages/core/src/runtime/utils/hashPropertyKey.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

Fixes #204.
Fixes #206.
---
In `resolveStyleRules()` & `compileCSS()` I renamed `pseudo` to `selectors` and changed their type to be `string[]`:
- To reflect what it contains as `selectors` can contain not only pseudo selectors.
- To handle selectors properly as it was a problem without a solution:
```ts
makeStyles({
":hover,:focus-within": {
"::before": {
color: "orange"
}
}
});
```
Before we were concatenating inputs with selectors and getting `":hover,:focus-within::before"` that will be compiled by Stylis to:
```css
.class:hover,.class:focus-within::before {}
```
And without proper wrapping with curly braces we cannot handle it. With selectors as an array with can send as input `:hover,:focus-within { ::before { } }` that will be handled properly.
Because before we didn't know scopes …

fix: handle nesting in comma separated selectors

---

change/@griffel-core-7c2fb1fa-c42f-4195-8948-dbac68156b32.json
packages/core/src/constants.ts
packages/core/src/types.ts

When teammates on Loop start working with Griffel, the shorthand type errors confuse them. There's no clear reason why the error shows up unless you know to look at Griffel's docs ahead of time. As most developers are just working with the Fluent UI library, they don't know to check here.
Adding back an interface for the unsupported shorthand properties makes this documentation easier to discover, as using "Go to definition" will link developers to the interface. I've added TSDoc comments to the overall interface as well as to each property.
Ideally the comments on the properties would show up when using makeStyles too, but I couldn't get that to work in VSCode. Nevertheless, I think this change helps developers understand why Griffel shows type errors for shorthands.

Add TSDoc to unsupported CSS properties

---

apps/website/src/components/Playground/code/app.js
apps/website/src/components/Playground/code/styles.js
apps/website/src/components/Playground/code/templates/selectors.js
apps/website/src/components/Playground/index.tsx
apps/website/tsconfig.json

Modifies the playground so that it inserts all the css rules into a style tag, and then outputs the real styles.
Obviously validation would be great, but a bit more complicated since [`stylis`](https://github.com/thysultan/stylis) already strips most invalid css styles. I'll try to tackle this in another PR. My idea would be to use this maybe [w3c-css-validator](https://www.npmjs.com/package/w3c-css-validator)
Currently, invalid CSS is just inserted as an empty rule, it's some validation but should be improved.

docs: show real inserted styles should be used in playground

---

.yarn/patches/@docusaurus-theme-common-npm-2.1.0-d5ae2a9539.patch
apps/website/sidebars.js
package.json
yarn.lock

Depends on #215. Fixes breabcrumbs on Try out page.
The PR adds a patch to `@docusaurus/theme-common` to handle hashes as a part of URL (I am not aware about any other way to handle it except ejecting the whole breadcrumb component).
It also changes items in a custom sidebar to group them into "Try out" category that will be used in breadcrumbs.

docs: fix breadcrumbs on try out pages

---

apps/benchmark/src/components/Select.tsx
apps/benchmark/src/implementations/types.ts
change/@griffel-react-eb078e75-469e-4056-b2e9-7293b007f909.json
packages/react/src/RendererContext.tsx
packages/react/src/TextDirectionContext.tsx

Fixes https://github.com/microsoft/griffel/issues/214

react: adding missing definition for "children" in props

---

.yarn/patches/mdx-mermaid-npm-1.3.2-e8a6432fce.patch
apps/website/docs/react/ahead-of-time-compilation/_category_.json
apps/website/docs/react/ahead-of-time-compilation/introduction.md
apps/website/docs/react/ahead-of-time-compilation/technical-details.md
apps/website/docs/react/ahead-of-time-compilation/with-babel.md
apps/website/docs/react/ahead-of-time-compilation/with-webpack.md
apps/website/docs/react/css-extraction/_category_.json
apps/website/docs/react/css-extraction/introduction.md
apps/website/docs/react/css-extraction/with-nextjs.md
apps/website/docs/react/css-extraction/with-webpack.md
apps/website/docs/react/guides/atomic-css.md
apps/website/docs/react/guides/build-time-transforms.md
apps/website/docs/react/guides/child-window-rendering.md
apps/website/docs/react/guides/limitations.md
apps/website/docs/react/install.mdx
apps/website/docusaurus.config.js
package.json
yarn.lock

~~Requires #215, #216.~~
- Updates a page about Atomic CSS with real content
- Adds pages about ahead-of-time compilation
- Adds pages about CSS extraction

docs: add pages about Atomic CSS, build time optimisations

---

change/@griffel-core-40e0578a-53de-40b8-9ed2-958d4fe70437.json
e2e/typescript/src/assets/fixture-reset.ts
e2e/typescript/src/test.mjs
packages/core/src/constants.ts
packages/core/src/index.ts
packages/core/src/makeResetStyles.test.ts
packages/core/src/makeResetStyles.ts
packages/core/src/renderer/getStyleSheetForBucket.test.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/runtime/resolveResetStyleRules.test.ts
packages/core/src/runtime/resolveResetStyleRules.ts
packages/core/src/types.ts

Fixes #225.
This PR implements `makeResetStyles()` function in `@griffel/core`.
- It generates a monolithic classes with `rf` prefix
- Produced CSS rules are insert into new `r` bucket, so any Atomic rules will have higher precedence
- Shorthands are allowed in `makeResetStyles` calls are there are no reasons to forbid them

feat: add makeResetStyles to @griffel/core

---

.github/workflows/extension.yml

Chrome extension publish pipeline is showing green but silently failing:
example run: https://github.com/microsoft/griffel/actions/runs/3180680715/jobs/5184550511
This PR change the github action for upload/publish extension to be https://github.com/marketplace/actions/publish-chrome-extension-to-chrome-web-store
This one will fail pipeline instead of failing silently:
example run: https://github.com/YuanboXue-Amber/griffel/actions/runs/3182423308/jobs/5188347275

chore: change github action for upload extension

---

.github/workflows/extension.yml

In extension.yml, I added a condition to only run deploy when `packages/devtools/package.json` is updated. This is nice, but it should be disabled when the workflow is triggered manually.

chore(extension workflow): always run deploy when triggering manually

---

change/@griffel-core-f0fa59fb-c3b5-470c-8e8d-667d83ed587f.json
change/@griffel-react-a509b887-05b6-42c0-8e64-331f4bc8f7bb.json
packages/core/bundle-size/makeResetStyles-runtime.fixture.js
packages/core/bundle-size/makeStylesRuntime.fixture.js
packages/react/bundle-size/makeResetStyles-runtime.fixture.js
packages/react/src/index.ts
packages/react/src/makeResetStyles.ts
packages/react/src/makeStyles.ts
packages/react/src/utils/isInsideComponent.ts

~~Requires #232.~~
Fixes #226.
---
This PR implements `makeResetStyles()` function in `@griffel/react`, see #225 for more context.
- `isInsideComponent` is moved to a separate file
- `makeResetStyles` is just a wrapper around `makeResetStyles` from `@griffel/core`
- Adds bundle size fixtures for `makeResetStyles` in `@griffel/core` & `@griffel/react`

feat: add makeResetStyles to @griffel/react

---

change/@griffel-core-8763d483-ffa6-4c7f-828d-2c0ddf69f21d.json
change/@griffel-react-1918fb6d-fdf8-469b-bd51-b049339020e2.json
packages/core/src/__resetStyles.ts
packages/core/src/index.ts
packages/react/src/__resetStyles.ts
packages/react/src/index.ts

A preparation for #236.
This PR adds `__resetStyles` to `@griffel/core` & `@griffel/react`. It works in the same way as existing `__styles` and is equal to `makeResetStyles`, but skips runtime work done in `resolveResetStyles`.

chore: add __resetStyles functions to core & react

---

change/@griffel-babel-preset-1db4e3d4-8a02-4dca-ac78-a24a1dbaecb7.json
packages/babel-preset/__fixtures__/error-argument-type/fixture.js
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts

Fixes a problem from https://github.com/microsoft/fluentui/pull/25216.
https://github.com/microsoft/griffel/blob/b360b562bc7180fa13c6d0a1979673983bfe5ee0/packages/babel-preset/src/transformPlugin.ts#L44-L46
The check that we have currently is too strict and breaks legit cases:
```
ERR! ERR! SyntaxError: /mnt/vss/_work/1/s/packages/react-components/react-button/src/components/Button/useButtonStyles.ts: makeResetStyles() function accepts only an object as a param
ERR! ERR!   13 | var buttonSpacingSmall = '3px';
ERR! ERR!   14 | var buttonSpacingMedium = '5px';
ERR! ERR! > 15 | var useBaseClassName = makeResetStyles(Object.assign({
ERR! ERR!      |                                        ^
ERR! ERR!   16 |   alignItems: 'center',
ERR! ERR!   17 |   boxSizing: 'border-box',
ERR! ERR!   18 | …
```

fix: relax check in transform plugin

---

change/@griffel-react-0c417873-8b81-4a7e-b68a-6f5fc2eb229b.json
packages/react/src/__resetCSS.ts
packages/react/src/index.ts

Follow up for #250.
- Fixes function name
- Exports `__resetCSS` function

fix: add export for __resetCSS

---

change/@griffel-core-f18356ed-6d74-4218-a44d-df648ef511ac.json
change/@griffel-jest-serializer-d855a4d4-e4c6-4f70-a258-c22caa4992ea.json
packages/core/src/__resetCSS.ts
packages/core/src/__resetStyles.ts
packages/core/src/constants.ts
packages/core/src/makeResetStyles.ts
packages/core/src/mergeClasses.test.ts
packages/core/src/mergeClasses.ts
packages/jest-serializer/src/index.test.tsx
packages/jest-serializer/src/index.ts

Fixes #261.
Fixes #230.
This PR modifies:
- `mergeClasses()` in Griffel core to emit errors if a call contains multiple occupancies of classes from `makeResetStyles`.
- Jest serializer to handle classes from `makeResetStyles`
Both changes uses new _global_ variable `DEBUG_RESET_CLASSES` to store classes. This works similarly to `DEFINITION_LOOKUP_TABLE`, but we need `DEBUG_RESET_CLASSES` only in development/tests so it has zero impact on production bundles.

feat: add validation into mergeClasses for makeResetStyles calls

---

change/@griffel-jest-serializer-75c22504-bc4b-439e-8717-b91254c209e1.json
packages/jest-serializer/src/index.test.tsx
packages/jest-serializer/src/index.ts

#260 added support for classes generated by `makeResetStyles`, the problem is that whitespaces were still present in output:
This PR fixes it.

fix(jest-serializer): handles whitespaces better

---

packages/webpack-extraction-plugin/__fixtures__/webpack/assets-multiple/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/assets/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/config-name/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/mixed/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-assets/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/reset/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/rules-deduplication/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/rules-deduplication/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/style-buckets/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/style-buckets/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/chunkA.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/chunkA.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/chunkB.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/chunkB.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/input.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/output.css
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts

This PR:
- removes usages of `console.log` to prefer usages of `export`
- adds a comment to `output.css` to identify from which files CSS comes
- updates `style-buckets` to include `@layer` & `@supports`
- adds `with-chunks` to assert chunks behavior
- adds `with-css` to ensure that we don't affect third-parties

chore: rework tests CSS extraction

---

change/@griffel-core-da60ef94-dd69-4128-9f8f-53fceb3ec3c3.json
change/@griffel-webpack-extraction-plugin-b995688a-9700-4878-8832-49047eed3bb3.json
packages/core/src/index.ts
packages/core/src/types.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets-multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/config-name/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/config-name/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/mixed/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset/output.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/parseCSSRules.test.ts
packages/webpack-extraction-plugin/src/parseCSSRules.ts
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts
packages/webpack-extraction-plugin/src/transformSync.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts

This PR changes the approach for sorting CSS rules in a produced CSS asset by `@griffel/webpack-extraction-plugin`.
We used `sortCSSRules` to parse CSS rules and sort them into buckets in the similar order as rules in `resolveStyleRules()`. However, it was not **the same way**.
The loader used for CSS extraction now emits comments to CSS to identify chunks and meta information (media queries case).
```css
/** @griffel:css-start [d] **/
.fe3e8s9 {
color: red;
}
/** @griffel:css-end **/
/** @griffel:css-start [m] [{"m":"screen and (max-width: 100px)"}] **/
@media screen and (max-width: 100px) {
.fr5o61b {
color: red;
}
}
/** @griffel:css-end **/
/** @griffel:css-start [m] [{"m":"screen and (max-width: 100px)"}] **/
@media screen and (max-width: 100px) {
.f1j0ers2 {
display: grid;
}
}
/** …
```

fix: use style buckets in CSS extraction

---

change/@griffel-babel-preset-3f5d5c23-15e4-450a-b8d7-eafa30001b48.json
packages/babel-preset/__fixtures__/keyframes/code.ts
packages/babel-preset/__fixtures__/keyframes/output.ts
packages/babel-preset/src/assets/normalizeStyleRules.test.ts
packages/babel-preset/src/assets/normalizeStyleRules.ts
packages/babel-preset/src/transformPlugin.test.ts

This PR fixes an issue with the babel plugin that errored when an array of animations was being passed to `animationName`. This happened because the plugin tried to parse each animation as an individual rule instead of as an object with rules inside of it.
- Fixes #275

fix: Babel plugin no longer errors on array values being passed to animationName

---

change/@griffel-webpack-extraction-plugin-d7a0320b-5a5b-44b3-8532-bfb6de7648f9.json
e2e/nextjs/project.json
e2e/typescript/project.json
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts

This PR refactors Webpack plugin for CSS extraction.
We use the same approach as [CompiledCSS](https://github.com/atlassian-labs/compiled/blob/40211567504538272f726085e7b5f8c7c4eb2255/packages/webpack-loader/src/extract-plugin.ts#L38-L69): we create a new `cacheGroup` in `optimization.splitChunks` and force all generated CSS files by us to go there.
As a result we will get a single asset (CSS file) that we can process and sort rules. This works, but this approach requires `optimization.splitChunks` to be **enabled**. One of our key partners has this setting **disabled** in dev environment: all try outs to enable it were not successful.
This approach also prevents all attempts to implement chunks splitting support and avoid a single CSS file.
TL;DR Does the same, works differently …

chore: rework CSS extraction

---

.yarn/patches/beachball-npm-2.31.5-0e84ec4233.patch
change/@griffel-webpack-extraction-plugin-4de53343-d0d0-448c-b7d5-edee0aa3facb.json
change/@griffel-webpack-loader-2410326a-c4ef-41e8-824d-f9d543e4ce90.json
package.json
packages/webpack-extraction-plugin/package.json
packages/webpack-extraction-plugin/src/webpackLoader.ts
packages/webpack-loader/__fixtures__/error-config/error.ts
packages/webpack-loader/package.json
packages/webpack-loader/src/webpackLoader.ts
yarn.lock

- Removes `loader-utils` & `schema-utils` from dependencies
- Bumps loader-utils in `yarn.lock` resolve security alerts
- Bumps beachball to resolve security alerts

chore: bump loader-utils, schema-utils and beachball

---

change/@griffel-webpack-extraction-plugin-46602e0c-3b1b-4553-a919-32df4dda9fd9.json
packages/webpack-extraction-plugin/__fixtures__/webpack/missing-calls/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/missing-calls/output.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/webpackLoader.test.ts

Fixes #266. More details in https://github.com/microsoft/griffel/issues/266#issuecomment-1340962907.
Our Babel plugin that strips runtime also returns a set of CSS rules in its metadata. Before this PR it always returned at least an empty object. Because of this the check below didn't work:
https://github.com/microsoft/griffel/blob/1289343d950319f48888cfe70c1c84af066f08db/packages/webpack-extraction-plugin/src/webpackLoader.ts#L68
As the check was passing always we were creating invalid imports for files that contain `__styles` as a string. [Files like that](https://github.com/microsoft/fluentui/blob/f3e6e65b7f6435dc6b09bfd626e99921a10983d8/packages/merge-styles/src/Stylesheet.ts#L90) were processed => got empty set of CSS rules => created an invalid import => crashed build.

fix: avoid empty CSS imports

---

change/@griffel-babel-preset-005f6c96-ccea-4fc1-b641-b97b741f7b2a.json
packages/babel-preset/__fixtures__/assets-urls/code.ts
packages/babel-preset/__fixtures__/assets-urls/output.ts
packages/babel-preset/src/assets/isAssetUrl.test.ts
packages/babel-preset/src/assets/isAssetUrl.ts
packages/babel-preset/src/assets/normalizeStyleRules.ts

Fixes #256.
_I still would like to normalize URLs, but didn't find about a good way to do that._
This PR removes quotes normalization for URLs that are not pointing to assets. For assets we can keep it as it just URL will be just a file path.

fix: do not always normalize quotes in url()

---

change/@griffel-webpack-extraction-plugin-bba7ffbb-7ebd-42a2-a707-04ab557a8d8f.json
packages/webpack-extraction-plugin/__fixtures__/webpack/assets-multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/mixed/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset/output.ts
packages/webpack-extraction-plugin/project.json
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.test.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/transformSync.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts
packages/webpack-extraction-plugin/virtual-loader/griffel.css
packages/webpack-extraction-plugin/virtual-loader/index.js

With changes in this PR we don't use this file anymore. The recipe is described in [Webpack's documentation](https://webpack.js.org/api/loaders/#inline-matchresource). It was impossible to do it before #277, but now we don't rely on `cacheGroups` anymore.
CSS was was emitted to a fake file `griffel.css` in the virtual loader, this file has a path that might look like `node_modules/@griffel/webpack-extraction-plugin/virtual-loader/griffel.css`. Image files are relative to the userland code
file, so we had to construct a relative path from the fake CSS file to the image file in userland code.
The fake `griffel.css` file is is under the same path as the original code file, so there is no need to do any changes to the image path since it will already be relative to the original code file.

chore: remove path magic in extraction process

---

change/@griffel-core-a8eb3726-f851-4e4b-835a-a1b792aec1db.json
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/getStyleSheetForBucket.test.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/types.ts

Exposes `styleElementAttributes` on `GriffelRenderer` so attributes could be accessed and applied to other elements.
Is done to unblock https://github.com/microsoft/fluentui/issues/25421.

feat: expose "styleElementAttributes" on GriffelRenderer

---

change/@griffel-eslint-plugin-e8795784-65dd-47ae-af56-2cd19703c5ae.json
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/hook-naming.md
packages/eslint-plugin/src/rules/hook-naming.test.ts
packages/eslint-plugin/src/rules/hook-naming.ts
packages/eslint-plugin/src/rules/no-shorthands.ts
packages/eslint-plugin/src/utils/helpers.ts

Fixes #213
Introduce a new linter rule to enforce the React hook naming pattern

Hook naming lint rule

---

change/@griffel-webpack-extraction-plugin-f9a0e45f-28d4-4e43-99e9-7783f2eace29.json
package.json
packages/webpack-extraction-plugin/__fixtures__/babel/alias/code.ts
packages/webpack-extraction-plugin/__fixtures__/babel/alias/output.ts
packages/webpack-extraction-plugin/__fixtures__/babel/basic/output.ts
packages/webpack-extraction-plugin/__fixtures__/babel/mixed/output.ts
packages/webpack-extraction-plugin/__fixtures__/babel/multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/babel/reset/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets-multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/mixed/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset/output.ts
packages/webpack-extraction-plugin/package.json
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.test.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
yarn.lock

This PR refactors Babel plugin that replace functions and extracts CSS in `@griffel/webpack-extraction-plugin`. The goal is to use references from imports instead of hardcoded names (`__resetStyles` & `__styles`).
The refactor is needed as we will use transforms from Linaria itself (#309) instead of ours. `@linaria/babel-preset` uses `@babel/helper-module-imports` to generate imports that don't collide in the scope (_which is better_):
```js
// Before
import { __css } from '@griffel/react';
// After
import { __css as _css } from '@griffel/react';
import { __css as _css2 } from '@griffel/react';
```
Internally the plugin is almost the same, but now it takes references via `path.scope.getBinding()` instead of trying to target hardcoded identifiers directly. This allows to be compatible with …

chore(webpack-extraction-plugin): refactor to support aliased imports

---

apps/website/docs/react/api/make-styles.md

The documentation was missing mention of pseudo-elements, more specifically the part about nested quotes being needed to successfully provide content to a pseudo-element.

docs: Add docs for pseudo elements

---

change/@griffel-core-d096f264-8c73-426c-b236-bcbf30ad8f49.json
packages/core/src/runtime/resolveResetStyleRules.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/warnAboutUnresolvedRule.test.ts
packages/core/src/runtime/warnAboutUnresolvedRule.ts

With this rule:
```
rule: {
'.my-class': {
...
}
}
```
Before:
Would fail to register and emit a `console.error` message indicating something was wrong.
After
Same behavior, but the message indicates an ampersand is missing in '.my-class'.

chore: adjust error messaging for rules which don't include ampersands

---

change/@griffel-webpack-extraction-plugin-1c5a4879-b2c1-43e5-af5e-7cca09556b45.json
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/output.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/transformSync.ts
packages/webpack-extraction-plugin/src/webpackLoader.test.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts

This PR adds `unstable_keepOriginalCode` to Webpack loader options in `@griffel/webpack-extraction-plugin`.
⚠️ **Please never use this option, it will be remove without further notice.**

feat: implement "unstable_keepOriginalCode" for extraction plugin

---

packages/eslint-plugin/README.md

Follow up for #282 (noticed that the rules was not added to README).

docs: add @griffel/hook-naming ESLint rule to README

---

change/@griffel-webpack-extraction-plugin-9ff1e7df-41e1-40ee-bc7e-6568075d0e22.json
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/chunkA.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/chunkB.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/output.css
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts
packages/webpack-extraction-plugin/src/GriffelDummyModule.ts

This PR fixes compatibility between our plugin and [`SplitChunksPlugin`](https://webpack.js.org/plugins/split-chunks-plugin/).
To process generated CSS `GriffelExtractionPlugin` required to have all CSS under `griffel` chunk. Before this PR `SplitChunksPlugin` could move out CSS from `griffel` chunk and leave unprocessed CSS.
```mermaid
graph TD
A[GriffelExtractionPlugin] -->|Moves generated CSS to `griffel` chunk| B[SplitChunksPlugin]
B -->|Moves out CSS from `griffel` chunk| C[GriffelExtractionPlugin fails to process all generated CSS]
```

fix: avoid conflicts with SplitChunksPlugin

---

.github/workflows/bundle-size.yml
.github/workflows/ci-change.yml
.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/extension.yml

- Actions have been bumped to latest versions
- Now cache for `yarn` is used from `actions/setup-node`
- `.github/workflows/ci.yml` have been simplified as we were running the same steps for `main` & PRs

chore: cleanup workflows

---

packages/webpack-extraction-plugin/__fixtures__/webpack/config-name/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/config-name/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/config-split-chunks/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-css/output.css
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts

This PR forces to run tests for extraction plugin in production mode, so Webpack will run its optimizations like module concatenation, empty chunks removal, etc. Minimizer are turned off to keep code readable.

chore: run tests for extraction plugin in production mode

---

change/@griffel-webpack-extraction-plugin-44513a3a-1173-4378-9fa4-f581f56dd195.json
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts

This fixes a real issue in the product, however I am struggling to write a test for this scenario.
All modules will be processed by `SplitChunks` as expected and moved to proper chunks ✅
```mermaid
graph LR
M1[moduleA.js] --> S{SplitChunks}
M2[moduleB.js] --> S
M3[moduleC.js] --> S
S --> C1[Chunk 1]
S --> C2[Chunk 2]
```
The expectation is that chunks will remain the same ("Chunk A" & "Chunk B") and it will be like that:
```mermaid
graph LR
M1[moduleA.js] --> S{SplitChunksPlugin}
M2[moduleB.js] --> S
M3[moduleC.js] --> S
MC1[moduleA.griffel.css] --> S
MC2[moduleB.griffel.css] --> S
MC3[moduleC.griffel.css] --> S
S --> C1[Chunk 1]
S --> C2[Chunk 2]
C1 --> GP{GriffelPlugin}
C2 --> GP
GP ---> CC[Griffel Chunk]
GP ---> CA1[Chunk 1]
GP ---> CA2[Chunk 2]
```
**However**, the reality is …

fix: handling modules with SplitChunksPlugin

---

change/@griffel-webpack-extraction-plugin-327c83f1-4269-4852-a1be-2a21887e293e.json
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/codeB.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/output.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts

Fixes #314.
This PR updates how `@griffel/webpack-extraction-plugin` will attach `griffel` chunk. The current way is updated to be under `unstable_attachToMainEntryPoint` option as still required by one of our partners. However, the plugin itself defaults into the behavior of `SplitChunksPlugin` as it does the same job.
> Note: `unstable_attachToMainEntryPoint` will be removed without a further notice, do not rely on it.

refactor: update how griffel chunk is attached

---

apps/website/docs/react/api/create-dom-renderer.md
change/@griffel-core-78fefbae-6966-49fb-b7cb-7f29a5dd05c7.json
packages/core/src/renderer/createDOMRenderer.test.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/getStyleSheetForBucket.test.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/react/README.md

Fixes #332.
This PR adds `insertionPoint` option. If specified, a renderer will insert created style tags after this element:
```js
import { createDOMRenderer } from '@griffel/react';
const insertionPoint = document.head.querySelector('#foo');
const renderer = createDOMRenderer(document, {
insertionPoint,
});
```
```html
<html>
<head>
<style id="foo" />
<style data-make-styles-bucket="d" />
<style id="bar" />
</head>
</html>
```

feat: add "insertionPoint" option to createDOMRenderer()

---

change/@griffel-webpack-extraction-plugin-93419209-40a5-47a0-90bc-1da1031b755a.json
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/output.ts
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts
packages/webpack-extraction-plugin/src/transformSync.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts

This PR re-implements `unstable_keepOriginalCode` (#323).
- Reverts changes (#323) in a Babel plugin as they are not needed
- Moves conditions directly to Webpack loader

chore(extraction-plugin): re-implement unstable_keepOriginalCode

---

change/@griffel-core-858c3d97-f959-46a8-94a1-4e8300b34885.json
packages/core/src/runtime/resolveResetStyleRules.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/warnAboutUnresolvedRule-node.test.ts
packages/core/src/runtime/warnAboutUnresolvedRule.ts

As both runtime and build time tools use the same functionality, we will emit warnings in build time. That was not intentional and confuses users, this PR hides warnings for Node env.

chore(core): hide warnings in Node

---

change/@griffel-eslint-plugin-a3b29662-7937-4c57-8d41-9ce578721b9f.json
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/styles-file.md
packages/eslint-plugin/src/rules/styles-file.test.ts
packages/eslint-plugin/src/rules/styles-file.ts

We've seen issues internally where our webpack bundle times have regressed when integrating the griffel CSS extraction plugins and loaders. We found that having all makeStyles in a .styles.ts file lets us limit the scope of where these plugins and loaders run to just files ending in .styles.ts which dramatically improved performance of our bundle tasks.
This code was heavily adapted from existing code by Yuanbo Xue in the Microsoft Teams repository.

Add a rule to enforce makeStyles calls only happen in .styles.ts files

---

change/@griffel-core-5ba8b312-008d-4c33-92c6-67ba1fa04e57.json
packages/core/src/shorthands/textDecoration.test.ts
packages/core/src/shorthands/textDecoration.ts
packages/core/src/shorthands/types.ts

feat(core): add shorthand for `text-decoration`

---

change/@griffel-babel-preset-5382e2de-3501-4289-9353-110f0d4e6865.json
change/@griffel-core-b58fd5c4-c0a8-4aea-967b-d3c75313e84e.json
change/@griffel-webpack-extraction-plugin-fd2d425f-98a5-450a-be39-c5c137f2fe32.json
package.json
packages/babel-preset/package.json
packages/core/package.json
packages/core/src/runtime/resolveResetStyleRules.test.ts
packages/webpack-extraction-plugin/package.json
yarn.lock

Fixes #373 by adopting a fix from https://github.com/thysultan/stylis/pull/313.

fix(core): bump stylis for proper @layer support in makeResetStyles

---

apps/website/docs/react/api/merge-classes.md

Called out that the resulting class name order might be different than the order passed to mergeClasses.  Noted that the final stylesheet is all that really matters.

Added some more info about class ordering to the mergeClasses documentation.

---

change/@griffel-webpack-extraction-plugin-f133a3fe-d85a-429a-b88e-77633804e494.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/ComponentA.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/ComponentB.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/chunk1.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/chunk2.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/code.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/fs.json
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/output.css
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/useBarStyles.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/useBazStyles.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/with-chunks-order/useQuxStyles.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts

This PR adds `experimental_resetModuleIndexes` to avoid warnings caused by `mini-css-extract-plugin`:
```
WARNING in chunk griffel [mini-css-extract-plugin]
Conflicting order. Following module has been added:
* css ./node_modules/css-loader/dist/cjs.js!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js?style=%2F**%20%40griffel%3Acss-start%20%5Bd%5D%20**%2F%0A.fm40iov%7Bcolor%3A%23ccc%3B%7D%0A%2F**%20%40griffel%3Acss-end%20**%2F%0A!./src/foo-module/baz.js
despite it was not able to fulfill desired ordering with these modules:
* css ./node_modules/css-loader/dist/cjs.js!./node_modules/@griffel/webpack-extraction-plugin/virtual-loader/index.js?style=%2F**%20%40griffel%3Acss-start%20%5Bd%5D%20**%2F%0A.f1e30ogq%7Bcolor%3Ablueviolet%3B%7D%0A%2F**%20%40griffel%3Acss-end%20* …
```

feat(webpack-extraction-plugin): add experimental_resetModuleIndexes

---

change/@griffel-core-17ae40bc-b25b-455e-900b-44ba24998b21.json
change/@griffel-shadow-dom-411ce7d0-962d-400a-8a6d-9c143208fd60.json
monosize.config.mjs
package.json
packages/core/src/index.ts
packages/core/src/renderer/createDOMRenderer.ts
packages/core/src/renderer/safeInsertRule.ts
packages/shadow-dom/.babelrc
packages/shadow-dom/.eslintrc.json
packages/shadow-dom/.storybook/main.js
packages/shadow-dom/.storybook/tsconfig.json
packages/shadow-dom/README.md
packages/shadow-dom/bundle-size/createShadowDOMRenderer.fixture.js
packages/shadow-dom/jest.config.ts
packages/shadow-dom/package.json
packages/shadow-dom/project.json
packages/shadow-dom/src/createFallbackRenderer.ts
packages/shadow-dom/src/createShadowDOMRenderer.ts
packages/shadow-dom/src/findInsertionPoint.test.ts
packages/shadow-dom/src/findInsertionPoint.ts
packages/shadow-dom/src/index.ts
packages/shadow-dom/src/stories/createShadowDOMRenderer.stories.tsx
packages/shadow-dom/src/stories/index.stories.tsx
packages/shadow-dom/src/types.ts
packages/shadow-dom/tsconfig.json
packages/shadow-dom/tsconfig.lib.json
packages/shadow-dom/tsconfig.spec.json
yarn.lock

Fixes #369.
Ports implementation from https://github.com/microsoft/fluentui-contrib/tree/main/packages/react-shadow.

feat(shadow-dom): introduce a render for Shadow DOM

---

change/@griffel-core-2d6dd71b-5fd3-4866-9472-5d90f34a392b.json
packages/babel-preset/__fixtures__/assets-urls/output.ts
packages/babel-preset/__fixtures__/assets/output.ts
packages/babel-preset/__fixtures__/keyframes/output.ts
packages/babel-preset/__fixtures__/object-mixins/output.ts
packages/babel-preset/__fixtures__/object-nesting/output.ts
packages/babel-preset/__fixtures__/shared-mixins/output.ts
packages/babel-preset/__fixtures__/tokens/output.ts
packages/core/src/devtools/getDebugTree.test.ts
packages/core/src/devtools/store.test.ts
packages/core/src/makeResetStyles.test.ts
packages/core/src/makeStaticStyles.test.ts
packages/core/src/makeStyles.test.ts
packages/core/src/runtime/__snapshots__/compileAtomicCSSRule.test.ts.snap
packages/core/src/runtime/compileAtomicCSSRule.test.ts
packages/core/src/runtime/compileCSSRules.ts
packages/core/src/runtime/compileKeyframeCSS.test.ts
packages/core/src/runtime/compileKeyframeCSS.ts
packages/core/src/runtime/prefixer.test.ts
packages/core/src/runtime/prefixer.ts
packages/core/src/runtime/resolveResetStyleRules.test.ts
packages/core/src/runtime/resolveStyleRules.test.ts
packages/react/src/createDOMRenderer.test.tsx
packages/react/src/renderToStyleElements-node.test.tsx

Copies the source from the [stylis prefixer](https://github.com/thysultan/stylis/blob/master/src/Prefixer.js) and updates it so that prefixing is only applied according the the browser support matrix. We follow the [browser support matrix](https://github.com/microsoft/fluentui/blob/master/rfcs/shared/build-system/06-browser-support-for-v9.md) of Fluent UI
Fixes #379

feat: Prefix according to browser support matrix

---

change/@griffel-style-types-88cd8fa1-371b-4c2e-bb29-0d88568c620d.json
e2e/typescript/src/assets/fixture.ts
e2e/typescript/src/assets/legacy/fixture-reset.ts
e2e/typescript/src/assets/legacy/fixture.ts
e2e/typescript/src/assets/legacy/tsconfig.fixture.json
e2e/typescript/src/test.ts
e2e/typescript/tsconfig.lib.json
e2e/utils/src/createTempDir.ts
packages/style-types/package.json
packages/style-types/src/legacy/README.md
packages/style-types/src/legacy/index.ts
packages/style-types/src/legacy/makeResetStyles.ts
packages/style-types/src/legacy/makeStaticStyles.ts
packages/style-types/src/legacy/makeStyles.ts
packages/style-types/src/makeResetStyles.ts
packages/style-types/src/makeStyles.ts

Fixes #378.
This PR introduces modern typings for TypeScript 4.1 and higher as this version supports recursive types references. This allow to simplify typings and remove weird workarounds. Also newer typings make TS errors more precise (check changes in the fixtures) 👍 
To keep compatibility with older versions of TS older typings are kept as legacy. To resolve them `typesVersions` field is used.

fix: introduce modern typings for TS >4

---

apps/website/docs/react/css-extraction/with-webpack.md
packages/webpack-extraction-plugin/README.md

This PR adds notes about usage of `ignoreOrder` option with `mini-css-extract-plugin`.

docs: add notes about `ignoreOrder` with `mini-css-extract-plugin`

---

change/@griffel-react-43329235-82d9-463b-aebe-f0609c2617bc.json
packages/react/jest.config.ts
packages/react/src/createDOMRenderer.test.tsx
packages/react/src/makeResetStyles.test.tsx
packages/react/src/renderToStyleElements.test.tsx

This modifies tests to use non-deprecated APIs from React 18. Also adds some new assertions to existing tests.

chore: use modern APIs in tests

---

change/@griffel-core-05c2915c-0733-4518-995d-e78d3784bc5e.json
packages/core/src/makeStaticStyles.ts
packages/core/src/runtime/resolveStaticStyleRules.test.ts
packages/core/src/runtime/resolveStaticStyleRules.ts

This PR reworks `resolveStaticStyleRules` to make it simpler and follow the same approach as `makeResetStyles` to unify insertion process.

chore: rework internals of makeStaticStyles

---

change/@griffel-core-970bda89-cefa-47c5-962d-a558027ec2cc.json
packages/core/src/shorthands/border.test.ts
packages/core/src/shorthands/border.ts
packages/core/src/shorthands/borderBottom.test.ts
packages/core/src/shorthands/borderBottom.ts
packages/core/src/shorthands/borderLeft.test.ts
packages/core/src/shorthands/borderLeft.ts
packages/core/src/shorthands/borderRight.test.ts
packages/core/src/shorthands/borderRight.ts
packages/core/src/shorthands/borderTop.test.ts
packages/core/src/shorthands/borderTop.ts
packages/core/src/shorthands/utils.ts

This PR adds functionality to `border*` shorthands functions to support the different order of arguments. For example,
```diff
border('2px')
+border('solid')
+border('none')
border('2px', 'solid')
+border('solid', '2px')
border('2px', 'solid', 'red')
+border('solid', '2px', 'red')
```
Fixes #393.

feat(core): support variadic arguments in border* shorthands

---

change/@griffel-core-7bc5ba3f-7967-411b-a0ce-d05321febf7f.json
package.json
packages/core/src/runtime/stylis/sortClassesInAtRulesPlugin.ts
yarn.lock

This PR bumps `@types/stylis` and removes `@ts-expect-error` in code.

chore: bump @types/stylis

---

change/@griffel-core-b81ce223-ebf6-413e-bd24-8908243f9ab4.json
packages/core/src/common/snapshotSerializers.ts
packages/core/src/makeResetStyles.test.ts
packages/core/src/makeStaticStyles.test.ts
packages/core/src/makeStyles.test.ts
packages/core/src/renderer/createDOMRenderer.test.ts
packages/core/src/runtime/resolveResetStyleRules.test.ts

This PR modifies existing snapshot serializers to emit bucket names in formatted CSS to make clearer what is generated.

chore: show bucket names in snapshots

---

change/@griffel-core-bfc4fd85-b03a-4200-88cc-14704f59ac47.json
packages/core/src/runtime/compileCSSRules.ts
packages/core/src/runtime/compileKeyframeCSS.ts
packages/core/src/runtime/stylis/prefixerPlugin.test.ts
packages/core/src/runtime/stylis/prefixerPlugin.ts

Moves `prefixerPlugin` to `/runtime/stylis` directory where all `stylis` related things live.

chore(core): move prefixer to stylis directory

---

change/@griffel-core-9d917d14-e85c-4ca7-beb7-164dcb0d6085.json
change/@griffel-react-a850ebd1-fc07-46c7-b8c7-3c97f8cfe864.json
change/@griffel-webpack-extraction-plugin-2982acb5-12ca-4655-8e1c-f048c923919f.json
packages/babel-preset/__fixtures__/reset-styles-at-rules/code.ts
packages/babel-preset/__fixtures__/reset-styles-at-rules/output.ts
packages/babel-preset/src/transformPlugin.test.ts
packages/core/src/__resetStyles.ts
packages/core/src/common/snapshotSerializers.ts
packages/core/src/makeResetStyles.test.ts
packages/core/src/makeResetStyles.ts
packages/core/src/renderer/getStyleSheetForBucket.test.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/runtime/compileResetCSSRules.test.ts
packages/core/src/runtime/compileResetCSSRules.ts
packages/core/src/runtime/resolveResetStyleRules.test.ts
packages/core/src/runtime/resolveResetStyleRules.ts
packages/core/src/runtime/stylis/isAtRuleElement.test.ts
packages/core/src/runtime/stylis/isAtRuleElement.ts
packages/core/src/runtime/stylis/rulesheetPlugin.test.ts
packages/core/src/runtime/stylis/rulesheetPlugin.ts
packages/core/src/runtime/stylis/sortClassesInAtRulesPlugin.test.ts
packages/core/src/runtime/stylis/sortClassesInAtRulesPlugin.ts
packages/core/src/types.ts
packages/react/src/__resetStyles.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-media/output.css
packages/webpack-extraction-plugin/src/babelPluginStripGriffelRuntime.ts

Fixes #403.
This PR introduces a new bucket ("s") for [at rules](https://developer.mozilla.org/en-US/docs/Web/CSS/At-rule) in `makeResetStyles`.
```html
<style data-bucket="r">
/** rules by makeResetStyles */
.foo { color: red }
@media (x) { color: green }
</style>
<style data-bucket="d">
/** rules by makeStyles */
.atomic { color: pink }
</style>
```
❌ The problem is `atomic` will override `@media (x)` rule because of the order of appearance.
```html
<style data-bucket="r">
/** rules by makeResetStyles */
.foo { color: red }
</style>
<style data-bucket="d">
/** rules by makeStyles */
.atomic { color: pink }
</style>
<style data-bucket="s">
/** rules by makeResetStyles */
.foo { color: red }
@media (x) { color: green }
</style>
```
✅ `atomic` overrides `foo`, but does not override `@media …

fix(core): makeResetStyles emits rules into separate buckets

---

change/@griffel-react-13bf5fac-a88b-41ad-98fc-a8df3be96e6d.json
packages/react/src/RendererContext.tsx
packages/react/src/__resetStyles.ts
packages/react/src/__styles.ts
packages/react/src/createDOMRenderer.test.tsx
packages/react/src/insertionFactory-node.test.ts
packages/react/src/insertionFactory.test.ts
packages/react/src/insertionFactory.ts
packages/react/src/makeResetStyles.ts
packages/react/src/makeStaticStyles.ts
packages/react/src/makeStyles.ts
packages/react/src/useInsertionEffect.ts
packages/react/src/utils/canUseDOM-node.test.ts
packages/react/src/utils/canUseDOM.test.tsx
packages/react/src/utils/canUseDOM.ts

Fixes #40.
This PR improves compatibility of `@griffel/react` by using a custom insertion factory that uses [`useInsertionEffect`](https://react.dev/reference/react/useInsertionEffect) when it's available.

chore: improve React 18 support

---

change/@griffel-webpack-loader-b9e23b96-1848-4762-8b00-bb466cbbe407.json
packages/webpack-loader/README.md
packages/webpack-loader/__fixtures__/webpack-resolve-options/code.ts
packages/webpack-loader/__fixtures__/webpack-resolve-options/color.jsx
packages/webpack-loader/__fixtures__/webpack-resolve-options/output.ts
packages/webpack-loader/src/schema.ts
packages/webpack-loader/src/webpackLoader.test.ts
packages/webpack-loader/src/webpackLoader.ts

The Outlook project has `webpack` build directly from Typescript source using `esbuild-loader`; to accomplish this, we define a `"source"` condition on all of our various package `"exports"` and specify it in `resolve.conditionNames` in `webpack.config.js`. The current behavior to lock this option to simply `["require"]` is a blocker to integrating the loader into our config.

Inherit more webpack resolve options

---

change/@griffel-eslint-plugin-de59e2ef-e29f-4852-bc03-5bf3b563f991.json
packages/eslint-plugin/README.md
packages/eslint-plugin/src/configs/recommended.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/src/rules/pseudo-element-naming.md
packages/eslint-plugin/src/rules/pseudo-element-naming.test.ts
packages/eslint-plugin/src/rules/pseudo-element-naming.ts
packages/eslint-plugin/src/utils/helpers.ts

This fixes #304.
It is basically the same rule as for `no-shorthands`, but instead of checking
whether the property is an `Identifier`, we check for `StringLiteral`.
Invalid Pseudo Element Names are:
`:before` and `:after`
Autofix works as intended:
```js
...
':before': {},
...
```
will fix to
```js
...
'::before': {},
...
```
Note: I am not the best programmer, so if you find something that should be changed or is not working as intended, let me know and I will try to fix it.

eslint-plugin: enforce pseudo element naming with :: over :

---

change/@griffel-babel-preset-84c90e38-9d5d-40cf-9ef9-ef07ef7886b5.json
packages/babel-preset/README.md
packages/babel-preset/src/index.ts
packages/babel-preset/src/schema.ts
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts
packages/babel-preset/src/types.ts
packages/babel-preset/src/validateOptions.test.ts

Adds a new plugin option `generateMetadata`.
Once this option is set, the babel preset will return metadata on the evaluated file containing Griffel styles in the below schema:
```ts
{
// makeStyles
cssEntries: {
// by each hook
useStyles1: {
// by each slot
root:  [ .fxxxxx { color: 'red' } ],
}
useStyles2: {
root:  [ .fxxxxx { color: 'red' } ],
},
},
// makeResetStyles
cssResetEntries: {
// by each hook
useResetStyles1: [ .fxxxxx { color: 'red' } ],
useResetStyles2: [ .fxxxxx { color: 'red' } ],
}
}
```
This metadata is intended for programmatic transforms in code that can be reused by other tooling:
```ts
const babelFileResult = Babel.transformFromAstSync(babelAST, sourceCode, {
babelrc: false,
configFile: false,
presets: [[griffelPreset, { generateMetadata: true }]],
filename: …
```

feat: Add metadata generation to babel preset

---

change/@griffel-webpack-extraction-plugin-2722342d-e7ad-42c7-b370-cc43d50217de.json
packages/webpack-extraction-plugin/__fixtures__/webpack/assets-flip/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets-multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/basic-rules/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/mixed/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/multiple/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset-assets/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/reset/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-attach-to-main/output.ts
packages/webpack-extraction-plugin/__fixtures__/webpack/unstable-keep-original-code/output.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts
packages/webpack-extraction-plugin/src/constants.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts
packages/webpack-extraction-plugin/virtual-loader/index.js

This change should have no impact on production build output. However, one issue I've noticed hen trying to migrate Outlook to use this is that our bundle-diff tool gets unwieldy with the massive module requests that embed the entire extracted CSS into the request.
Instead, this change stores the extracted CSS in a map in the plugin, and uses an enhancement to the loader context to read and write the CSS in the map. As a result, we can eliminate the `?styles=<css>` part of the module request.

Stop inlining the CSS in the virtual CSS module request

---

change/@griffel-style-types-ce9ebd17-8bff-4a8f-977b-21c6d5621021.json
e2e/typescript/src/assets/fixture-reset.ts
e2e/typescript/src/assets/fixture.ts
e2e/typescript/src/test.ts
packages/style-types/package.json
packages/style-types/src/makeResetStyles.ts
packages/style-types/src/makeStyles.ts

Fixes an issue with `animationName` (fixes #417) to allow usage of CSS variables in `animationName`. The fix is done for modern typings as legacy typings already allow it.
To make it strict, new syntax with template literals. Legacy types now used for TS 4.3 and earlier.

fix(style-types): allow CSS variables in animationName

---

apps/website/docs/react/api/merge-classes.md

Small doc update to provide an explicit example of combining the generated scoped classes from Griffel with arbitrary space-delimited class strings. 
As per discussion here: https://github.com/microsoft/griffel/issues/424

Update mergeClasses doc to explain combining griffel classes with custom classes

---

change/@griffel-postcss-syntax-d4ee585a-66da-45c9-91ac-92a8b8f828be.json
package.json
packages/postcss-syntax/.babelrc
packages/postcss-syntax/.eslintrc.json
packages/postcss-syntax/README.md
packages/postcss-syntax/jest.config.ts
packages/postcss-syntax/package.json
packages/postcss-syntax/project.json
packages/postcss-syntax/src/constants.ts
packages/postcss-syntax/src/createSyntax.ts
packages/postcss-syntax/src/index.ts
packages/postcss-syntax/src/location-preset.ts
packages/postcss-syntax/src/parse.test.ts
packages/postcss-syntax/src/parse.ts
packages/postcss-syntax/src/stringify.ts
packages/postcss-syntax/src/transform-sync.ts
packages/postcss-syntax/tsconfig.json
packages/postcss-syntax/tsconfig.lib.json
packages/postcss-syntax/tsconfig.spec.json
tsconfig.base.json
workspace.json
yarn.lock

Implements a postcss [custom syntax](https://postcss.org/docs/how-to-write-custom-syntax) for Griffel that can parse JS code into the output CSS and does a limited mapping of the resulting postcss AST back to the original JS code.
More details are in the new package README

feat: Implment postcss custom syntax for Griffel

---

change/@griffel-babel-preset-11c81df7-855c-49d5-9b5d-28141fa0884c.json
package.json
packages/babel-preset/package.json
yarn.lock

Bumps `@linaria/babel-preset` to ensure that the version with a fix is picked (https://github.com/callstack/linaria/pull/1335).
Also did `yarn dedupe` on `yarn.lock`.

chore: bump @linaria/babel-preset

---

change/@griffel-babel-preset-96f2826d-0876-42d6-8ef0-f3dbd6c45004.json
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts

If the user configures the preset to generate metadata, the objects should be defined by default to align with typings.
This fixes the edge case where the preset runs on a file without Griffel - in a backwards compatible way.

fix: metadata entries should be defined by default

---

change/@griffel-core-514d4515-c4ba-47ce-81d3-9c6c3426e82e.json
packages/core/src/runtime/resolveStyleRules.test.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/utils/hashClassName.ts
packages/core/src/runtime/utils/hashPropertyKey.test.ts
packages/core/src/runtime/utils/hashPropertyKey.ts
packages/core/src/runtime/utils/trimSelector.test.ts
packages/core/src/runtime/utils/trimSelector.ts

Fixes #431.
This PR updates hash generation for properties and classes to trim selectors before hash will be generated. Currently only the case with `> ` is handled.
New tests added for matching scenarios.

fix(core): trim ">" selector

---

change/@griffel-eslint-plugin-aaff19e9-c0d8-41c3-b258-2458bd8cbb7f.json
packages/eslint-plugin/src/rules/hook-naming.test.ts
packages/eslint-plugin/src/rules/hook-naming.ts
packages/eslint-plugin/src/rules/no-shorthands.test.ts
packages/eslint-plugin/src/rules/no-shorthands.ts
packages/eslint-plugin/src/rules/pseudo-element-naming.test.ts
packages/eslint-plugin/src/rules/pseudo-element-naming.ts
packages/eslint-plugin/src/rules/styles-file.ts
packages/eslint-plugin/src/utils/helpers.ts

Updates the lint rules to consistently check `makeResetStyles` and `makeStaticStyles`, not just `makeStyles`.

feat: update all rules to lint makeResetStyles and makeStaticStyles

---

change/@griffel-core-05e2f791-537a-45f8-82e7-5145a7745834.json
packages/core/src/runtime/__snapshots__/compileAtomicCSSRule.test.ts.snap
packages/core/src/runtime/compileAtomicCSSRule.test.ts
packages/core/src/runtime/stylis/prefixerPlugin.test.ts
packages/core/src/runtime/stylis/prefixerPlugin.ts

Fixes #457.
The PR restores prefixing for `background-clip: text` case.

fix(core): restore prefixing for "background-clip: text"

---

change/@griffel-core-37cc7380-d4cc-4151-8ad7-c78576d587f7.json
packages/core/src/runtime/stylis/prefixerPlugin.test.ts
packages/core/src/runtime/stylis/prefixerPlugin.ts

Removes prefixing for `ms-` rules as we don't support IE and legacy Edge.

chore(core): remove prefixing for "ms-"

---

change/@griffel-webpack-extraction-plugin-593a69cc-cc81-40f5-af41-6bce970f9e8f.json
change/@griffel-webpack-loader-0c8121e6-efb9-45f6-bba1-42cfc2b86834.json
packages/webpack-extraction-plugin/src/webpackLoader.ts
packages/webpack-loader/src/webpackLoader.ts

Fixes #465 by adding an explicit check for `null` to `parseSourceMap` utility.

Fix inputSourceMap Babel error

---

change/@griffel-core-f665f81b-8374-4996-981e-c3191ff46cc4.json
packages/core/src/shorthands/gridArea.test.ts
packages/core/src/shorthands/gridArea.ts

Fixes #469.
```js
gridArea('header1')  // => 
// {
//   gridRowStart: 'header1',
//   gridColumnStart: 'auto',
//   gridRowEnd:  'auto',
//   gridColumnEnd:  'auto',
// }
```
```js
gridArea('header1')  // => 
// {
//   gridRowStart: 'header1',
//   gridColumnStart: 'header1',
//   gridRowEnd: 'header1',
//   gridColumnEnd: 'header1',
// }
```

fix(core): improve detection of custom idents in shorthands.gridArea()

---

change/@griffel-react-0fc8fc0d-e86d-4cbd-bc14-a56fe7e4cc07.json
packages/react/package.json

Adds `wyw-in-js` field to `package.json` to support styles processing with WyW-in-JS compiler (https://wyw-in-js.dev/). The plan is to use this compiler for Vite/esbuild plugins (https://github.com/microsoft/griffel/pull/41) and later switch our Webpack loader to it (https://github.com/microsoft/griffel/pull/414).

chore(react): add "wyw-in-js" field for tag processor

---

change/@griffel-shadow-dom-0964b9c8-3382-4396-aebb-8fefcd90f377.json
packages/shadow-dom/src/createShadowDOMRenderer.test.ts
packages/shadow-dom/src/createShadowDOMRenderer.ts
packages/shadow-dom/src/findInsertionPoint.test.ts
packages/shadow-dom/src/findInsertionPoint.ts
packages/shadow-dom/src/index.ts

Exposes the `insertionPoint` API for shadow DOM similar to vanilla Griffel.
[See Fluent UI Contrib for more details](https://github.com/microsoft/fluentui-contrib/issues/59).

feat(shadow-dom): add `insertionPoint` to `createShadowDOMRenderer()` options

---

apps/website/docs/react/ahead-of-time-compilation/with-vite.md

Looks like there was a typo, and instead of _With Vite_ the page's header with _With Webpack_.

fix: updates heading ahead of time compilation > with vite

---

change/@griffel-webpack-extraction-plugin-7334bfc7-abbd-4b74-a335-a5ceb1421fa6.json
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.test.ts
packages/webpack-extraction-plugin/src/GriffelCSSExtractionPlugin.ts

This PR adds `unstable_attachToEntryPoint` config option that replaces `unstable_attachToMainEntryPoint`. To migrate please do:
```diff
new GriffelCSSExtractionPlugin({
- unstable_attachToMainEntryPoint: true,
+ unstable_attachToEntryPoint: 'main',
})
```

feat(webpack-extraction-plugin): add "unstable_attachToEntryPoint" option

---

change/@griffel-postcss-syntax-c809b309-b523-4995-97f3-b6f4c4e27cea.json
packages/postcss-syntax/package.json
packages/postcss-syntax/src/parse.ts

Fixes the postcss syntax so that it has the correct entrypoint path. Also creates an extractor for babel plugin options since postcss can sometimes pass more things into options.

fix(postcss-syntax): entrypoint to be correct path

---

change/@griffel-jest-serializer-584b8140-267b-4569-be55-89a684191ee4.json
packages/jest-serializer/src/index.test.tsx
packages/jest-serializer/src/index.ts

The `test` function for the serializer plugin is called many times (from jest docs)
> Pay attention to efficiency in test because pretty-format calls it often.
https://github.com/jestjs/jest/tree/main/packages/pretty-format#test
Using the serializer for many elements causes a large slowdown due to the fact it constructs a large regex every time it's called
I believe this can be improved because
1. Both `DEBUG_RESET_CLASSES` and `DEFINITION_LOOKUP_TABLE` are maps so we should be able to lookup a class without doing a string search
1. classes will always be space separated in the string, so we can split the string by spaces to isolate individual classes
This PR changes the `test` function to use a faster implementation
Simple benchmark test - https://jsperf.app/nevedi

Improve speed of serializer test function

---

change/@griffel-eslint-plugin-bca332e9-8e32-4b7d-b684-845410f81adb.json
packages/eslint-plugin/tsconfig.json
packages/eslint-plugin/tsconfig.lib.json

Fixes #505.
`@griffel/eslint-plugin` was accidentally built as ESM that caused failures when ESLint tried to load the module.

fix: build @griffel/eslint-plugin as CJS

---

change/@griffel-eslint-plugin-6c46ffbc-f2b8-4ee8-8082-1f74398823df.json
packages/eslint-plugin/src/index.ts

Follow up for #521. Needed to produce `module.exports = plugin`.

fix: update export in @griffel/eslint-plugin

---

change/@griffel-babel-preset-0b574090-5363-4d0e-bdea-7fb46436796a.json
packages/babel-preset/__fixtures__/error-on-undefined/fixture.ts
packages/babel-preset/__fixtures__/error-on-undefined/tokens.ts
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/utils/evaluatePathsInVM.ts

Related to #513.
Improves error handling: instead of cryptic "don't know how to turn this value into a node" we will throw an original error.

chore: improve error reporting

---

change/@griffel-style-types-1902f2bf-3bed-4124-992b-7cbfc8bf05ba.json
e2e/typescript/src/assets/legacy/fixture.ts
packages/style-types/src/legacy/makeStyles.ts

The same as #511, but for legacy types.

fix: use custom fallback type for legacy types

---

change/@griffel-webpack-extraction-plugin-8c8cbb98-803e-46ce-9061-62ebe75fc727.json
packages/webpack-extraction-plugin/src/generateCSSRules.test.ts
packages/webpack-extraction-plugin/src/generateCSSRules.ts
packages/webpack-extraction-plugin/src/webpackLoader.ts

The PR improves CSS generation inside the webpack loader from `@griffel/webpack-extraction-plugin`. That makes output shorter and removes special handling for `media` bucket.
(comments are generated for every rule)
```css
/** @griffel:css-start [d] [{}] **/
.baz { color: orange; }
/** @griffel:css-end **/
/** @griffel:css-start [d] [{}] **/
.foo { color: red; }
/** @griffel:css-end **/
/** @griffel:css-start [d] [{}] **/
.qux { color: magenta; }
/** @griffel:css-end **/
```
(rules are merged into blocks)
```css
/** @griffel:css-start [d] [{}] **/
.baz { color: orange; }
.foo { color: red; }
.qux { color: magenta; }
/** @griffel:css-end **/
```

chore: improve CSS generation

---

e2e/nextjs/src/test.ts
e2e/rspack/src/test.ts

`@griffel/babel-preset` was not packed and used from NPM in tests instead of a local copy.

chore: pack @griffel/babel-preset in E2E tests

---

change/@griffel-core-6531b53b-a58e-43cc-bb63-61c68cda8172.json
change/@griffel-webpack-extraction-plugin-1f7409f0-d60c-4d7b-a773-716a0087becb.json
packages/core/src/common/snapshotSerializers.ts
packages/core/src/constants.ts
packages/core/src/makeStyles.test.ts
packages/core/src/renderer/createDOMRenderer.test.ts
packages/core/src/renderer/createIsomorphicStyleElement-node.test.ts
packages/core/src/renderer/createIsomorphicStyleSheet.test.ts
packages/core/src/renderer/createIsomorphicStyleSheet.ts
packages/core/src/renderer/getStyleSheetForBucket.test.ts
packages/core/src/renderer/getStyleSheetForBucket.ts
packages/core/src/renderer/rehydrateRendererCache.test.ts
packages/core/src/renderer/rehydrateRendererCache.ts
packages/react/src/renderToStyleElements-node.test.tsx
packages/react/src/renderToStyleElements.test.tsx
packages/webpack-extraction-plugin/src/generateCSSRules.test.ts
packages/webpack-extraction-plugin/src/generateCSSRules.ts
packages/webpack-extraction-plugin/src/parseCSSRules.test.ts
packages/webpack-extraction-plugin/src/parseCSSRules.ts
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

This PR adds support for additional `priority` property in `meta` of CSS rules, this allows to order CSS rules based on it.
For example:
```ts
const rules = [
'.bar { color: blue }',
['.foo { color: red }', { p: -1 }],
]
```
Will produce following CSS:
```css
.foo { color: red }
.bar { color: blue }
```
These changes are needed to support CSS shorthands.
- `sortCSSRules()` have been refactored to have clearer implementation
- Snapshots in `sortCSSRules()` have been updated to be clearer

chore: add support for priority in CSS rules

---

change/@griffel-webpack-extraction-plugin-6ce6c02b-7add-4430-8e51-b247db585301.json
packages/webpack-extraction-plugin/src/sortCSSRules.test.ts
packages/webpack-extraction-plugin/src/sortCSSRules.ts

Followup for #539.
Priority of CSS rules had higher priority in sort than buckets order. This PR fixes it.

fix: fix sorting of buckets in sortCSSRules()

---

change/@griffel-postcss-syntax-720ba521-03ed-452a-a58e-df0e483e8c6b.json
packages/postcss-syntax/src/parse.ts
packages/postcss-syntax/src/transform-sync.test.ts
packages/postcss-syntax/src/transform-sync.ts

When using @griffel/postcss-syntax `parse` on TS code:
```ts
parse(`import type { Something } from 'somwhere'`, {
babelOptions: {
presets: ["@babel/preset-typescript"],
},
});
```
It throws error 💥 `Unexpected token, expected "from"`.
This happens because `presets` config is not used when transforming code with Babel.
This PR takes the `babelOptions` presets/plugins and use it during transform.

fix(postcss-syntax): throw error when parsing TS

---

change/@griffel-babel-preset-b78df94c-317a-4354-9d27-a58f703e2c16.json
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts

With styles like `...shorthands.padding(0)`, the metadata generated from babel-preset contains 6 css rules, with padding-left/padding-right duplicated. This PR removes the duplicate so the result will be 4 css rules as expected.

fix(babel-preset): remove duplicated styles from the generated metadata

---

change/@griffel-core-6be177be-0e28-4c2b-b669-fbf43322e4aa.json
packages/core/src/runtime/compileAtomicCSSRule.test.ts
packages/core/src/runtime/compileAtomicCSSRule.ts
packages/core/src/runtime/getStyleBucketName.test.ts
packages/core/src/runtime/getStyleBucketName.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/utils/hashClassName.ts
packages/core/src/runtime/utils/hashPropertyKey.test.ts
packages/core/src/runtime/utils/hashPropertyKey.ts
packages/core/src/runtime/utils/types.ts

Performs internals refactor to reduce number of arguments in `resolveStyleRules()`.

chore: refactor at rules to be a separate param in functions

---

change/@griffel-babel-preset-5f01fbba-7bfc-453f-9e5b-60dcdaf7f65f.json
change/@griffel-core-1200d9cd-dfd9-46bd-b88a-6c2a7b30a7e7.json
packages/babel-preset/__fixtures__/config-classname-hash-salt/code.ts
packages/babel-preset/__fixtures__/config-classname-hash-salt/output.ts
packages/babel-preset/src/schema.ts
packages/babel-preset/src/transformPlugin.test.ts
packages/babel-preset/src/transformPlugin.ts
packages/babel-preset/src/types.ts
packages/core/src/resolveStyleRulesForSlots.ts
packages/core/src/runtime/resolveResetStyleRules.ts
packages/core/src/runtime/resolveStyleRules.ts
packages/core/src/runtime/utils/hashClassName.test.ts
packages/core/src/runtime/utils/hashClassName.ts
packages/vite-plugin/project.json
packages/webpack-loader/__fixtures__/config-classname-hash-salt/code.ts
packages/webpack-loader/__fixtures__/config-classname-hash-salt/output.ts
packages/webpack-loader/src/webpackLoader.test.ts

This PR adds `classNameHashSalt` option for Babel plugin & Webpack loader.
The option will be properly documented once it will be implemented also for runtime.

feat: add "classNameHashSalt" for AOT

---

change/@griffel-core-3f1edf4d-9560-425a-bd42-e112f2ced10f.json
e2e/rspack/src/snapshots/output.css
packages/babel-preset/__fixtures__/at-rules/output.ts
packages/babel-preset/__fixtures__/rules-with-metadata/output.ts
packages/core/src/runtime/resolveStyleRules.test.ts
packages/core/src/runtime/utils/hashClassName.test.ts
packages/core/src/runtime/utils/hashClassName.ts
packages/core/src/runtime/utils/hashPropertyKey.test.ts
packages/core/src/runtime/utils/hashPropertyKey.ts
packages/react/src/createDOMRenderer.test.tsx
packages/react/src/renderToStyleElements-node.test.tsx

See issues for reproductions:
- Fixes #559
- Fixes #561
Adds prefixes for at rules in hashes so they will be unique.

fix(core): fix hash collisions with at rules

---

change/@griffel-webpack-loader-3fba1f5a-ce6b-4d64-ad46-b17ca2db5949.json
packages/webpack-loader/__fixtures__/webpack-resolve-plugins/fake-color.ts
packages/webpack-loader/src/schema.ts
packages/webpack-loader/src/webpackLoader.test.ts

Fixes schema for `webpackResolveOptions.plugins` in `@griffel/webpack-loader`.

fix(webpack-loader): fix schema for webpackResolveOptions.plugins

---

change/@griffel-core-f62e4d27-94b5-466e-b76a-b36e48520a8f.json
packages/core/src/runtime/warnings/warnAboutUnresolvedRule.ts
packages/core/src/runtime/warnings/warnAboutUnsupportedProperties.ts

Warnings were leaking to production code:
Fixes #581.

chore: remove development warnings from production code

---

change/@griffel-jest-serializer-a5cad9b7-42a8-4a48-b2ba-e8218d04c1e9.json
packages/jest-serializer/src/index.test.tsx
packages/jest-serializer/src/index.ts

Follow up for #583.
Fixes a case when element has only a class defined by `makeResetStyles()` was not removed.

fix(jest-serializer): fix reset class handling

---

change/@griffel-postcss-syntax-8e694cac-d57f-4ce3-9862-ae1bf76fc16a.json
packages/postcss-syntax/src/location-preset.ts
packages/postcss-syntax/src/parse.test.ts
packages/postcss-syntax/src/parse.ts
packages/postcss-syntax/src/transform-sync.test.ts

Adds comment directive parsing in the location preset so that that comments starting with `griffel-` are collected with styles metadata.
```ts
const useStyles = makeStyles({
// griffel-csslint-disable color-no-hex   
slot: {
color: '#fff'
},
});
// griffel-csslint-disable color-no-hex
const useResetStyles = makeResetStyles({
color: '#fff'
})
```
Updates the parser to transform `griffel-csslint-disable` to `styleint-disable` comments in output CSS for attached style slots. The above example outputs to
```css
.fxxx { color: red } /* stylelint-disable-line color-no-hex */
.rxxx {  color: red } /* stylelint-disable-line color-no-hex */
```

feat: Support stylelint rule disabling for style slots

---

change/@griffel-eslint-plugin-af581fe2-88f5-44cb-bb57-3d71b2cfcf03.json
packages/eslint-plugin/README.md

no-invalid-shorthand-argument is already implemented but was missing from the README.
Fixes #589

docs(eslint-plugin): add missing rule to README

---

change/@griffel-react-5ca90ea3-fea9-40d2-bce5-e49a8d6d1928.json
package.json
packages/react/.eslintrc.json
packages/react/src/RendererContext.tsx
yarn.lock

Adds the [React Compiler eslint plugin](https://react.dev/learn/react-compiler#installing-eslint-plugin-react-compiler) to enforce the [Rules of React](https://react.dev/reference/rules) via linting.
See related: https://github.com/microsoft/fluentui/pull/31457

chore: add `eslint-plugin-react-compiler` to React package

---

change/@griffel-react-b38d1a6d-6d8d-471e-8e44-e3722096edd2.json
packages/react/src/RendererContext.tsx

Changes the code to strictly follow the [Rules of Hooks](https://react.dev/reference/rules/rules-of-hooks).
Previously the code conditionally called a hook which prevents React Compiler from making any potential optimizations. Now the conditional has been moved inside the hook.
However, this code is still potentially problematic as we are relying on [`useMemo()` for correctness rather than as a performance optimization](https://react.dev/reference/react/useMemo):
Depends on #565

fix: remove eslint exception in `RendererProvider`

---

change/@griffel-eslint-plugin-dd20b1e1-c272-409a-95f9-19ca824187ce.json
packages/eslint-plugin/README.md
packages/eslint-plugin/src/rules/styles-file.ts
packages/eslint-plugin/src/rules/top-level-styles.md
packages/eslint-plugin/src/rules/top-level-styles.test.ts
packages/eslint-plugin/src/rules/top-level-styles.ts
packages/eslint-plugin/src/utils/helpers.ts

Hey folks! This adds a new `top-level-styles` eslint rule to forbid using the `makeStyles`, `makeResetStyles` and `makeStaticStyles` methods anywhere other than in the top-level of a file. 
It's kind of opinionated, so I understand if you don't want to accept the PR, but it seems like a reasonable linting rule addition to the "recommended" lint settings, even if it's more restrictive for developers. 
We're using Fluent 9 + Griffel in our app + recently ran into a variety of build errors once we imported a new set of packages.  Several package authors were misusing the Griffel methods (`makeStyles` in particular) and passing in runtime variables. In every case, they'd create a helper method that was doing the job of calling makeStyles.  
By forcing developers to always call these methods …

feat(eslint-plugin): add top-level-styles eslint rule

---

change/@griffel-core-e0dc7909-f321-4c3e-b9f8-0a2a280e37cf.json
packages/core/src/shorthands/border.ts
packages/core/src/shorthands/borderBottom.ts
packages/core/src/shorthands/borderLeft.ts
packages/core/src/shorthands/borderRight.ts
packages/core/src/shorthands/borderTop.ts
packages/core/src/shorthands/gridArea.ts
packages/core/src/shorthands/inset.ts
packages/core/src/shorthands/margin.ts
packages/core/src/shorthands/outline.ts
packages/core/src/shorthands/padding.ts
packages/core/src/shorthands/textDecoration.ts
packages/core/src/shorthands/transition.ts

Deprecated tag is needed for all overloads of deprecated shorthand functions to communicate that a shorthand is deprecated
Because of https://github.com/microsoft/TypeScript/issues/407, deprecation notices are not coming through today when there are multiple overloads of a deprecated shorthand function
When there are no overloaded functions, deprecation notices come through

Deprecation notices for all deprecated shorthands

---

change/@griffel-postcss-syntax-466b35ec-0bf1-4ddb-9e0e-381079132a98.json
packages/postcss-syntax/src/location-preset.ts
packages/postcss-syntax/src/parse.test.ts
packages/postcss-syntax/src/parse.ts
packages/postcss-syntax/src/transform-sync.test.ts

For below code:
```js
import { makeStyles } from "@griffel/react";
const styles = {
root: {
color: "red",
},
};
export const useStyles = makeStyles(styles);
```
Location preset returns empty location `{}`. But when `parse` is trying to access the location of the slot by `locations["useStyles"]["root"]`, it throws error since `locations["useStyles"]` is undefined.
Location preset now returns the location of the makeStyles/makeResetStyles call as well.
For the above case, when `parse` sees `locations["useStyles"]?.["root"]` is undefined, it uses the location of the call expression `callExpressionLocations["useStyles"]`

fix(postcss-syntax): return location of the makeStyles/makeResetStyles call expression if slots can't be located

---

change/@griffel-devtools-f10a728e-3ede-491b-b048-924af4a9ec5e.json
packages/devtools/project.json
packages/devtools/webpack.config.js

_If Nx upgrade broke nothing, you simply don't know what it broke._
Updates configs to include `index.html` into artifacts & excludes runtime chunk.

fix(extension): include `index.html` in publish

---

change/@griffel-postcss-syntax-1b3c650d-9bdd-461c-8b2c-45a33787c1eb.json
packages/postcss-syntax/src/parse.test.ts
packages/postcss-syntax/src/parse.ts

Persists the correct filename during postcss parsing so that any resulting error messages will have the correct filename path instead of an autogenerated `<input cdfsdf/>` -like hash

fix: Persist filename in postcss syntax

---

change/@griffel-postcss-syntax-d160ba10-518b-4f99-8afa-1b6647679cfb.json
packages/postcss-syntax/src/parse.test.ts
packages/postcss-syntax/src/parse.ts

If a result is silenced it should still be usable by the syntax `stringify`. This PR adds the `GRIFFEL_SRC_RAW` property to the root make that possible.

fix(postcss-syntax): Silenced parse result should be stringifiable

---

change/@griffel-core-f40a63ca-515a-4e89-af69-997821bf5130.json
packages/core/src/renderer/getStyleSheetForBucket.ts

Some frameworks like Remix/ReactRouter v7 perform full-document hydration on the client side. When the hydration fails, React attempts to recover by re-rendering the entire tree multiple times on the client side. During this process, FluentUI and Griffel enter an infinite loop because the `window.document` might not be fully ready; it exists but lacks head/body elements.
- Clone the https://github.com/dmytrokirpa/fluentui-remix/blob/main
- Remove the `patches` directory
- Run `yarn install && yarn dev`
- Open the app in a browser with any extension that patches the DOM (e.g., DarkReader)
https://github.com/user-attachments/assets/6a8d3a06-7dc9-4cb0-b0ba-809af6aee340
The style tag is added to the head only if `document.head` is actually available.
**Note:** There will be a similar patch to …

fix: fix infinite loop caused by hydration errors in React 18

---

apps/website/docs/react/api/make-static-styles.md

Clarifies that `fontFamily` may need to be quoted in certain cases. This is an easy thing to get wrong so I thought it best we document it.
[Correct usage](https://griffel.js.org/try-it-out/?code=JYWwDg9gTgLgBAbziAhgawKYGUYpsAYxwE8AbDAZzgF84AzKCEOAcgAEBzKYOujUgPQFoGFgG4AUBIwAPSLDgATDHRQBXUvFSYceQiXIUAFAglxWbOhAB2MALSqCogFyIz5%2BjZgAxFCGCkxK4sAERYGBwQGHAAqgCScADqGABGcEbJFDAYUNZwAKJqjGAYKNYAlCEsADTu5hRQBK4ABqQQBCikRmERUbFxIeXVcG0dXT2RGPGDtR4eReMAFjAwYBTOAkIAdBR2-gSMFBB0MFvCIAJZegQCVrYUl70YdmrAAgDulPYYRRAlZQJrNBUIJSHgvlt3sc6AAmQZ1OaeKCoGDdKG8OFDBHmBbdZardabAg7PaEQ7HU7nS64fA3O4wB4UJ4vN6fLJ2H7FUrWQHAzoCMHZLKQ6HwxEeKzIvBo0VY8W4kL4tYbba7fbkk5nJjU663LyM5mvD5fDm-f48oFS0Hg4UrOhi8VIlHdGBQNQYGDEEqDZqzCVeZLADjLVwAFgADOG4AIAFRwS0guAxgR%2B6i1ajlSRAA)
[Incorrect …

docs: add a note about using fontFamily in makeStaticStyles

---

README.md
apps/website/docusaurus.config.js
azure-pipelines.yml

GitHub is spelled with a capital H. This fixes user-facing usage of `Github` by changing it to `GitHub`.

Use capital H in GitHub
